### ISSUE TITLE
Namespace conflict with Official Facebook SDK for Unity

### ISSUE THREAD

**Issue by BonyYousuf** [Microsoft/winsdkfb#102]
Hi,
I am using this SDK with Unity. And unfortunately both the new official Facebook SDK for unity version 7.3.0 and this SDK has same "Facebook" namespace. Now I can't build my project anymore for this conflict. 

What can I do to solve this problem?
Thanks

**Comment by adiviness** [comment]
#71 made several changes to the naming, for now it has only been merged into the `develop` branch. It will eventually make its way to `master` but in the meantime you can build the sdk from the `develop` branch. The renaming did create some incompatibilities so you will need to update references and regenerate some files as outlined in the pull request.

**Comment by BonyYousuf** [comment]
Hi,
Thanks for your support. I am not very familiar with c++. So instead i have renamed Unity's Facebook SDK. For now it works. Later when this will come in master i will update my code

**Comment by alakshmi1030** [comment]
Please reopen if there are any more issues/questions regarding this.
