### ISSUE TITLE
C++ UWP - Documentation to Fix + 4 Tips (LogoutAsync, FeedDialog Logout, FeedDialog Empty, Polling)

### ISSUE THREAD

**Issue by AlanGusLive** [Microsoft/winsdkfb#103]
Hi,

I'm using the FBSDK-UWP/C++. In C++ parts of the documentation http://microsoft.github.io/winsdkfb/, can you please replace "ShowFeedDialog" and "ShowRequestsDialog" by "ShowFeedDialogAsync" and "ShowRequestsDialogAsync"?

I share you 4 tips for your SDK.

Tips N°1: LogoutAsync(...)

With this function I can't connect another user. To connect another user I added the following code in the LogoutAsync(...) function to delete the cookies. In "https" the "s" is very important to find the "secure" cookies and delete them.

	HttpBaseProtocolFilter^ filter = ref new HttpBaseProtocolFilter();
	HttpCookieCollection^ cookieCollection;
	for (int iCounter = 0; iCounter <= 1; iCounter++)
	{
		if (iCounter == 0)
		{
			cookieCollection = filter->CookieManager->GetCookies(ref new Uri("https://m.facebook.com"));
		}
		else
		{
			cookieCollection = filter->CookieManager->GetCookies(ref new Uri("https://www.facebook.com"));
		}

		int i = 0;
		int iNbCookies = cookieCollection->Size;

		while (i < iNbCookies)
		{
			filter->CookieManager->DeleteCookie(cookieCollection->GetAt(i));
			i = i + 1;
		}
	}
	
	
Tips N°2: FeedDialog

When the FeedDialog is displayed, in the Facebook menu, I can select on the right, the menu "Déconnexion" (in French), may be "log out" for you. In this case a logout request is automatically send to Facebook and all the cookies are deleted but the token is not deleted. So I added in the FacebookDialog.xaml.cpp in the function dialogWebView_FeedNavStarting(...) a new test to call the LogoutAsync() and to stop the webview:

	else if (IsLogoutRedirect(e->Uri))
	{
		dialogWebBrowser->Stop();

		UninitDialog();

		DebugPrintLine(L"Feed response is " + e->Uri->DisplayUri);
		FBSession^ sess = FBSession::ActiveSession;
		sess->LogoutAsync();

		FBError^ err = FBError::FromJson(ref new String(ErrorObjectJson));
		_dialogResponse = ref new FBResult(err);

	}

	bool FacebookDialog::IsLogoutRedirect(
		Uri^ Response
		)
	{
		return (String::CompareOrdinal(Response->Path, FACEBOOK_LOGOUT_PATH) == 0);
	}	
		
	#define FACEBOOK_LOGOUT_PATH  L"/logout.php"	

Tips N°3: As I had said in #67 there is a FeedDialog Empty in a specific sequence, this is all the steps I used to fix it:

- In the FBAccessTokenData, the AccessToken and the Expiration date are saved. I added the save of 2 cookies: "xs" and "c_user"
- In the FacebookSession, I added a boolean "_bLoadedFromExistingToken" to know if the user used a login/password or the token
- I added the 2 cookies in the cookieManager before showing the FeedDialog, but only when the session was loaded by the token. (When the user used a login/password, with the tool Fiddler4, I can see some duplicated cookies).
```
	void FacebookDialog::ShowFeedDialog(
		PropertySet^ Parameters
		)
	{
		TypedEventHandler<WebView^, WebViewNavigationStartingEventArgs^>^ handler =
			ref new TypedEventHandler<WebView^, WebViewNavigationStartingEventArgs^>(
				this, &FacebookDialog::dialogWebView_FeedNavStarting);

		FBSession^ sess = FBSession::ActiveSession;

		if (sess->_bLoadedFromExistingToken == true)
		{
			Uri^ uri = BuildFeedDialogUrl(Parameters);

			FBAccessTokenData^ FBAccessTokenData = sess->AccessTokenData;

			HttpBaseProtocolFilter^ filter = ref new HttpBaseProtocolFilter();
			HttpCookieManager^ cookieManager = filter->CookieManager;

			HttpCookie^ c_userCookie = ref new HttpCookie("c_user", uri->Host, "/");
			c_userCookie->Value = FBAccessTokenData->_c_userCookie;

			HttpCookie^ xsCookie = ref new HttpCookie("xs", uri->Host, "/");
			xsCookie->Value = FBAccessTokenData->_xsCookie;

			cookieManager->SetCookie(c_userCookie, false);
			cookieManager->SetCookie(xsCookie, false);
		}

		ShowDialog(ref new DialogUriBuilder(this,
			&FacebookDialog::BuildFeedDialogUrl), handler, Parameters);
	}	
```
Tips N°4: Polling
In the ShowFeedDialogAsync, ShowRequestsDialogAsync and ShowLoginDialog I saw the remark: "// TODO: Is there a better way to do this?  I was using an event, but the concurrency event object was deprecated in the Win10 SDK tools. Switched to plane old Windows event, but that didn't work at all, so polling for now."

In Win 10 or before, you can use a concurrency::task_completion_event<void> to manually decide when a task is completed. You can find a sample here: https://msdn.microsoft.com/en-us/library/hh873181%28v=vs.110%29.aspx

You can close this issue if you haven't any question and you have fixed the documentation.

Regards,
AlanGusLive

**Comment by TedHoward** [comment]
fyi for the project team,
#2 & #3 mean that our app has features live on Google+ & iOS but not on WinRT. We had to disable Facebook feed posts on WinRT but not on android (2 soon to be 4 appstores) or on iOS.
Any other app team using this SDK will also likely hobble their WinRT version ... if they even notice this semi-complicated repro bug.

**Comment by alakshmi1030** [comment]
@AlanGusLive: thanks for the tips. Regarding documentation, the wording has been fixed pending our updated documentation to the website which will go live soon. Regarding your tip 1, see #31 for guidance on logout. As for the other tips, please provide a pull request and we can investigate/repro to see if these can be merged into our SDK. 

@TedHoward thanks for the information - we will keep that in mind as we update our SDK.

**Comment by AlanGusLive** [comment]
Hi alakshmi1030,

I added a pull request : "Fix when using Facebook Menu to log out in a FeedDialog #103 (Tip N°2)"

Regards,
AlanGusLive

**Comment by alakshmi1030** [comment]
We accepted your pull request, and new documentation is now live at:

http://microsoft.github.io/winsdkfb/
