### ISSUE TITLE
"AuthenticateAsync is unavailable for releases beginning with Windows Phone 8.1"

### ISSUE THREAD

**Issue by fmonts** [Microsoft/winsdkfb#104]
I'm getting this error when building. What does this mean? I can't release the app for wp8.1 or later? 
I don't know c++ so I have no idea how to fix this... 

> \winsdkfb-master\FBWinSDK\FBWinSDK\FBWinSDK.Shared\FacebookSession.cpp(760): warning C4973: 'Windows::Security::Authentication::Web::WebAuthenticationBroker::AuthenticateAsync' : marked as deprecated
1>          Message: 'AuthenticateAsync is unavailable for releases beginning with Windows Phone 8.1. Instead, use AuthenticateAndContinue or AuthenticateSilentlyAsync'

**Comment by adiviness** [comment]
It means that the function `WebAuthenticationBroker::AuthenticateAsync` is not available on windows phone 8.1. You'll still be able to pass the windows app certification kit with the function there but if you try to call it from an 8.1 app on windows phone 8.1 it will throw an exception. It won't affect you if you don't try to log in via `SessionLoginBehavior::WebAuth` on a windows 8.1 phone. I have silenced this warning in our `develop` branch for now.
