### ISSUE TITLE
App request forces user to log in each time application is run

### ISSUE THREAD

**Issue by SultanSulejman** [Microsoft/winsdkfb#105]
App requests seem to ignore already acquired token and require entering logging credentials each time application is run despite the fact that user is already logged in. After additional logging in, app requests works fine until user restarts application.

Problem can be reproduced on sample app (LoginCpp) on Windows 8.1. Facebook fails to use passed token and launches login dialog as stated in stripped and decoded logs:
```
Redirect URI is https://www.facebook.com/connect/login_success.html
Navigating to https://www.facebook.com/v2.1/dialog/apprequests?access_token=C...M&redirect_uri=https://www.facebook.com/connect/login_success.html&client_id=1...5&title=I love Brussels Sprouts!&message=Om Nom Nom!
Path is /v2.1/dialog/apprequests
Navigating to https://www.facebook.com/login.php?skip_api_login=1&api_key=1...5&signed_next=1&next=https://www.facebook.com/v2.4/dialog/app_requests?redirect_uri=https%3A%2F%2Fwww.facebook.com%2Fconnect%2Flogin_success.html&access_token=C...M&title=I+love+Brussels+Sprouts%21&message=Om+Nom+Nom%21&client_id=1...5&ret=login&cancel_url=https://www.facebook.com/connect/login_success.html?error_code=4201&error_message=User+canceled+the+Dialog+flow#_=_&display=page
Path is /login.php
Navigating to https://www.facebook.com/login.php?login_attempt=1&next=https://www.facebook.com/v2.4/dialog/app_requests?redirect_uri=https%3A%2F%2Fwww.facebook.com%2Fconnect%2Flogin_success.html&access_token=C...M&title=I+love+Brussels+Sprouts%21&message=Om+Nom+Nom%21&client_id=1...5&ret=login&lwv=101
Path is /login.php
Navigating to https://www.facebook.com/v2.4/dialog/app_requests?redirect_uri=https://www.facebook.com/connect/login_success.html&access_token=C...M&title=I+love+Brussels+Sprouts!&message=Om+Nom+Nom!&client_id=1...5&ret=login&ext=1450649390&hash=Aeb8iIQ64-HiHVrb
Path is /v2.4/dialog/app_requests
Navigating to https://www.facebook.com/connect/login_success.html#_=_
Path is /connect/login_success.html
Request response is https://www.facebook.com/connect/login_success.html#_=_
```

**Comment by panagorn** [comment]
I have the same issue. When i open my app after i close it session.LoggedIn is always false. Did you find anything?

**Comment by alakshmi1030** [comment]
To clarify, is the issue that when you close the app and reopen it, you have to re-enter the login credentials due to an expired token? If you are using the WebView for login then the access token you receive is short-term (expiring within 2 hours), so that might be the issue. If that is the case, you will have to go through the server side authentication flow with that token to receive a long-term token (60 day expiration). See the documentation/guidance on that on facebook's developer page here: https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension

**Comment by alakshmi1030** [comment]
Please reopen if you are still experiencing this issue.
