### ISSUE TITLE
ShowRequestDialog not sending any invite

### ISSUE THREAD

**Issue by LaurentTermeau** [Microsoft/winsdkfb#108]
I've implemented a ShowRequestDialog step in my UWP app as discribed in the sample code. The Dialog show the Preview properly as well as the list of friend to whom I want to send the invite. It executes properly an return proper Succeed = true, as well as a RequestId, but the targetted user never receives any notification. 
The 2 users involved are Friends, the sender has got all the proper Permissions, the Application (the Test One) is registered as a Game App.
Do I miss Something ? or is there is missing feature in the current SDK version ?

**Comment by alakshmi1030** [comment]
Is your app live? The person receiving the app request (target user) should be an admin/dev/tester against your app I believe.

**Comment by alakshmi1030** [comment]
If you are still being affected by this problem, please feel free to reopen this issue.
