### ISSUE TITLE
User Information

### ISSUE THREAD

**Issue by alizargham** [Microsoft/winsdkfb#110]
How to pull user information like age range, birthday and e.t.c?

**Comment by alakshmi1030** [comment]
you need to make a graph api request (once the user has logged in, authenticated and approved your app's permissions) to /me?fields=birthday,age_range

See here for more information: https://developers.facebook.com/docs/graph-api/reference/user

**Comment by jerrak0s** [comment]
@alakshmi1030 Can you provide a code snippet for that situation ? 
How to deal with access token and a simple request for uwp?

**Comment by alakshmi1030** [comment]
Try this code snippet in C#:
                
                PropertySet parameters = new PropertySet();
                string path = "/me?fields=birthday,age_range";

                var factory = new FBJsonClassFactory(s => {
                    return JsonConvert.DeserializeObject<FBReturnObject>(s);
                });

                var singleValue = new FBSingleValue(path, parameters, factory);
                var result = await singleValue.PostAsync();

Note you will need an FBReturnObject class like this one:

           public class FBReturnObject
           {
                    public string Id { get; set; }
                    public string Post_Id { get; set; }
           }

**Comment by jerrak0s** [comment]
@alakshmi1030  I am getting a 
System.Collections.EmptyReadOnlyDictionaryInternal when PostAsync().

**Comment by alakshmi1030** [comment]
Sorry, I believe it should be:

    singleValue.GetAsync()

because it is a get request, not post request.

**Comment by jerrak0s** [comment]
@alakshmi1030  and how to set AccessTokenData ? Because i get
An active access token must be used to query information about the current user.

**Comment by adiviness** [comment]
AccessTokenData is set on a successful login with `FBSession::LoginAsync()`.
