### ISSUE TITLE
LoginAsync after LogoutAsync doesn't work in Native App

### ISSUE THREAD

**Issue by rastaputin** [Microsoft/winsdkfb#112]
Using the SDK, I created a windows universal native app.  Following the directions on a couple of sites (which were all similar):
https://blogs.windows.com/buildingapps/2015/07/14/windows-sdk-for-facebook/

The app works as expected the first time:
1) Native app window loads
2) manually press the "login" button
  - a webview covers the app and allows for Facebook login

3) Login success, webview disappears, token is available on the FBSession object.

Running the app again:
1) run app
2) press login button
3) user is immediately signed in.  (great).

I added a "logout" button, which just calls "logoutAsync" and it functions as I would expect.  The user is logged out. 

HOWEVER:
running the app again, when I press the **login** button now:
- the webview covers the app as expected, but there is an error message:
"Not Logged In:  You are not logged in. Please login and try again".

NO KIDDING?  I called the "loginAsync( somePermissions)" and you're telling me to login!  That's what I'm trying to do.

This api/sdk is super easy to use, which is great.. but unless I'm doing something wrong, it is broken for use with a native app.  Either something in LogoutAsync is not clearing (under the covers) properly, or LoginAsync has a bug (because I can see that the session is logged out, and its not presenting the 'login' view).

Thank you.

**Comment by alakshmi1030** [comment]
Which branch are you using - develop or master? Would be helpful for us to see if we can repro the issue. Regarding logout, there is a closed issue related to the implementation for LogoutAsync and how the SDK is following Facebook's official guidance for logging out: #31

**Comment by adiviness** [comment]
I'm not able to repro this, feel free to reopen if this is still affecting you. For what it's worth, we're currently reviewing #119 which if merged should help with the problem.
