### ISSUE TITLE
SDK Reference not working

### ISSUE THREAD

**Issue by gregoiredumas** [Microsoft/winsdkfb#113]
Hi,
I have added the FBSDK-UWP.csproj to my project, referenced it in my app references yet when I follow the documentation, "using Facebook;" does not work as it says that the namespace could not be found.
Am I missing something or do I have a problem with my solution?

**Comment by alakshmi1030** [comment]
Are you pulling from the master branch or the develop branch? There is a breaking change in the develop branch which renames the namespace as "winsdkfb".

**Comment by gregoiredumas** [comment]
I'm not sure to get what you mean by that, could you elaborate please?

**Comment by alakshmi1030** [comment]
What I meant is there are different versions of the SDK on the "master" branch and "develop" branch here on GitHub. However, your issue might be due to the fact that the Facebook SDK build did not complete fully in Visual Studio before you ran the project.

**Comment by gregoiredumas** [comment]
I see, I have the one from the master branch. The error shows up when i type the "using Facebook;" so it's before i run anything.
[http://imgur.com/KvWyJRA](url) A screenshot of my solution explorer, if it can be of any help.

**Comment by alakshmi1030** [comment]
So the error will show up before you build the solution - Visual Studio will throw an error before you run because it doesn't the SDK being built. Try right clicking on your solution "Hubber" and "Build Solution" and run your project after that and see if it works.

**Comment by gregoiredumas** [comment]
Ok, it doesn't work, I get a bunch of errors:
[http://imgur.com/uEfRehD](url)

**Comment by alakshmi1030** [comment]
Could you try building just the Facebook project without building your "Hubber" solution entirely? It could be that the path is too long to the directory where you have our SDK cloned.

**Comment by adiviness** [comment]
Are there files in `%root_dir_path%\winsdkfb\winsdkfb\winsdkfb.Shared\Generated`? If there isn't, try building the sdk for either desktop or phone exclusively and let us know if it fixed the problem.
