### ISSUE TITLE
Unable to login with WebView

### ISSUE THREAD

**Issue by FrankIceBass** [Microsoft/winsdkfb#115]
When you enable "Web OAuth Login" in facebook settings and you specify a redirect URI, you won't be able anymore to login with WebView.

**Comment by alakshmi1030** [comment]
Which redirect URI are you specifying?

**Comment by FrankIceBass** [comment]
I'm sorry, I forget to specify that I'm speaking about WebView authentication. When you enable "Web OAuth Login", Facebook forces you to set a redirect uri in the textbox below called: "Valid OAuth redirect URIs". From this time, you won't be able to login in facebook because the redirect uri parameter in the login request is always: "https://www.facebook.com/connect/login_success.html" and not, for example, "http://<myredirect>/".
To solve this problem is enough to add a new property in the FBSession called, for example, "RedirectUri". Change the part in which you compose and check the request in FacebookDialog.xaml.cpp and modify FacebookAccessTokenData.cpp in the function: "FBAccessTokenData::ParametersFromResponse" to parse correctly request fragmets.

Thank you.
FdR

**Comment by adiviness** [comment]
For webview dialogs you will now be able to specify custom redirect urls using `FBSession::SetWebViewRedirectUrl` in the `develop` branch.
