### ISSUE TITLE
Feed Dialog always return Posting failed

### ISSUE THREAD

**Issue by AlanGusLive** [Microsoft/winsdkfb#116]
Hi,

In your sample (LoginCpp-UWP.sln), when I post with a Feed Dialog, I always receive a Posting failed because the response of the api facebook is "https://www.facebook.com/connect/login_success.html#_=_" and the "post_id" is NOT in the response.

In the FacebookDialog.xaml.cpp in the function dialogWebView_FeedNavStarting(...) the following "request" is always nullptr because there is no "post_id":
``
FBFeedRequest^ request = FBFeedRequest::FromFeedDialogResponse(e->Uri);
``

May be you can ignore the check of the "post_id" in the response?
Do you think that it's possible to receive a path with "/connect/login_success.html" with a Failed post?

As you can see the missing "post_id" is a bug in Facebook api : https://developers.facebook.com/bugs/206102013075665/
They just tell to use Share Dialog instead the Feed Dialog but it's not a solution for me.

Regards,
AlanGusLive

**Comment by alakshmi1030** [comment]
Does it say "posting failed" and the post doesn't get shared to the user's timeline? Or is it just saying failed even though it succeeded?

**Comment by AlanGusLive** [comment]
It just saying failed even though it succeeded. I can see the message in the users's timeline but I received "posting failed".

**Comment by AlanGusLive** [comment]
Hi,

It works now. I can see that Facebook has changed something because before the cancel button in the FeedDialog was in the state unactivate and now it is activate. Now I receive the "post_id" after a post.

I close this issue.

Regards,
AlanGusLive
