### ISSUE TITLE
crush when no internet connection

### ISSUE THREAD

**Issue by salos1982** [Microsoft/winsdkfb#117]
Log in with internet connection
switch off internet connection
try to get any data from facebook
result -> crush in rethrow exception

	IAsyncOperation<String^>^ FBClient::GetTaskAsync(
		String^ path,
		PropertySet^ parameters
		)
	{
		return create_async([=]()
		{
			HttpBaseProtocolFilter^ filter = ref new HttpBaseProtocolFilter();
			HttpClient^ httpClient = ref new HttpClient(filter);
			cancellation_token_source cancellationTokenSource =
				cancellation_token_source();
			bool containsEtag = false;

			filter->CacheControl->ReadBehavior = HttpCacheReadBehavior::Default;

			Uri^ uri = FBClient::PrepareRequestUri(HttpMethod::Get, path, 
				parameters, nullptr, nullptr, containsEtag, nullptr);

			return create_task(httpClient->GetAsync(uri), 
				cancellationTokenSource.get_token())
			.then([=](HttpResponseMessage^ response)
			{
				return create_task(response->Content->ReadAsStringAsync(), 
					cancellationTokenSource.get_token());
			})
			.then([=](task<String^> resultTask)
			{
				String^ result = nullptr;
				try
				{
					result = resultTask.get();
				}
				catch (const task_canceled&)
				{
				}
				catch (Exception^ ex)
				{
				   throw ex;
				}

				return result;
			});
		});
	}

**Comment by adiviness** [comment]
We'll look into this some more, the fact that `FBClient::GetTaskAsync` rethrows the exception is wrong. Ultimately the sdk should be catching the exception elsewhere and turning it into an `FBError` that would be attached to any `FBResult` that is returned to the user.

**Comment by adiviness** [comment]
This should be fixed in the `develop` branch as of 1db5953ed260221a81fbaae0cf815eb2c1a20535, please reopen the issue if it still occurs.
