### ISSUE TITLE
Need to add a property set to JSON objects

### ISSUE THREAD

**Issue by ekalbredneb** [Microsoft/winsdkfb#12]
All of the generated JSON objects defined in the SDK can have more properties than our code currently recognizes.  For example, the FBPage object currently parses out the fields id, category, checkins, description, likes, link, and name.  Beyond, those, however, Facebook defines a very large available schema for a page (https://developers.facebook.com/docs/graph-api/reference/page), any or all of which may be available for a given page.  Developers will at some point want access to some or all of these items, if they're available, so they need to be made available through some kind of mechanism like a property set.  Modifying the base template for code generation should allow us to add a property set and populate it with any unknown properties, that client apps can then query for any data they wish.

**Comment by adiviness** [comment]
A change for this is merged into `develop` as of 385f4b68df7a28a89872d6790665e7cb30d4798a.
