### ISSUE TITLE
How to upload GPS track?

### ISSUE THREAD

**Issue by MichalGruszka** [Microsoft/winsdkfb#123]
How to share fitness.walk?

**Comment by alakshmi1030** [comment]
Could you point us to the Facebook Developer docs which talks about GPS tracks? Then I should be able to show you how to publish it using our SDK.

**Comment by MichalGruszka** [comment]
I want to create something like this. 
![bez tytulu](https://cloud.githubusercontent.com/assets/17600098/13508702/619465b2-e188-11e5-80b7-c6cd3e6caa06.jpg)

I have .gpx file of such data.
<trkpt lat="50.65359221" lon="17.90527239"> <ele>188</ele><time>2016-03-03T08:21:17Z</time></trkpt>

I think I should use Open Graph Stories and fitness.walks or fitness.course but I do not know how.

Thank you for your help.

**Comment by adiviness** [comment]
I don't believe that you can upload .gpx files directly to Facebook using their graph api. Please feel free to reopen this issue if you find a related graph endpoint.
