### ISSUE TITLE
WebView login on Windows Phone 8.1 has wonky UI

### ISSUE THREAD

**Issue by adiviness** [Microsoft/winsdkfb#125]
On Windows Phone 8.1 the "X" for closing the dialog is weirdly proportioned and the dialog's text fields for entering the Facebook login details get obscured by the keyboard. The problem occurs on phone emulators for Windows 8.1 and 10, I haven't tried a physical phone yet. Windows 10 apps on mobile emulator don't exhibit this issue.

**Comment by jamesfdickinson** [comment]
It also looks weird on the my wp8.1 device (520). the "X" for closing the dialog is weirdly proportioned.

**Comment by adiviness** [comment]
This has been fixed for a while in the `master` branch.
