### ISSUE TITLE
Having the Facebook app installed prevents login

### ISSUE THREAD

**Issue by Thunkar** [Microsoft/winsdkfb#128]
Using the UWP version. Just updated to the latest version on the master branch, which I understand that tries to login via the official app (in case it is installed) instead of using the webview. The code that previously worked results in this screen after the app shows the initial splash:

![wp_ss_20160309_0001 1](https://cloud.githubusercontent.com/assets/5404052/13620232/843c6696-e58e-11e5-9e4a-38b5d6f53868.png)

SDK 10586, Lumia 925 on Windows 10.10586.107, FB app 10.2.2.0

Works fine on desktop or uninstalling the facebook app, as it launches the webview.

**Comment by alakshmi1030** [comment]
We are looking into this, for now you can specify the `SessionLoginBehavior.WebView` in the `LoginAsync` function to go back to the WebView login behavior.

**Comment by Thunkar** [comment]
Thanks for the fast response! The workaround is fine for the moment, works great.

**Comment by khouzam** [comment]
Are you passing permissions to your login request. If not, we seem to crash when using the app. We'll look at fixing this.

Thanks.

**Comment by adiviness** [comment]
`SessionLoginBehavior::WebAccountProvider` login flow (which is the default for win10 mobile devices) should now be fixed in the `develop` branch. please reopen the issue if this bug is still occurring.
