### ISSUE TITLE
UWP - close button under status bar

### ISSUE THREAD

**Issue by igorkulman** [Microsoft/winsdkfb#130]
I have a UWP app. On phone when I set the status bar to a different color (including Opacity = 1 to make it work), the close button for the Facebook login dialog is partially hidden under the status bar.

![fb](https://cloud.githubusercontent.com/assets/4746070/13730500/8756d782-e951-11e5-928f-1082e8712a99.png)

**Comment by khouzam** [comment]
Thanks. I've accepted your pull request.
