### ISSUE TITLE
"The application called an interface that was marshalled for a different thread."

### ISSUE THREAD

**Issue by Elminday** [Microsoft/winsdkfb#137]
I am currently using masters branch and with this code: http://pastebin.com/pwRgwnCG and on line 
FBResult result = await sess.LoginAsync(BuildPermissions()); Permissions are built correctly.
I get an error that: "The application called an interface that was marshalled for a different thread" while trying to LoginAsync

**Comment by adiviness** [comment]
How are you calling your `LoginFacebook` function? Which platform and Windows version are you seeing the error on?

**Comment by Elminday** [comment]
I call on the button "click" method. My target device on project is Windows
phone Silverlight 8.1, however dependency is Windows phone 8.1. I hse
Visual Studio 2015

On 6 Apr 2016 20:26, "adiviness" <notifications@github.com> wrote:
>
> How are you calling your LoginFacebook function? Which platform and
Windows version are you seeing the error on?

**Comment by adiviness** [comment]
Nothing is jumping out at me with your code as being the cause of the problem, but I am unable to repro it. If the samples work ok then are you able to provide a project that reliably causes the error?

**Comment by adiviness** [comment]
After further investigation it seems that this is a problem with instantiating our `FacebookDialog` class in a silverlight project. This would explain why the samples are working but not your project as well. I'm afraid we don't support silverlight or have plans to support it.

**Comment by Elminday** [comment]
How can I change project from silverlight to to just 8.1 without
silverlight?

2016-04-29 22:22 GMT+03:00 adiviness <notifications@github.com>:

**Comment by adiviness** [comment]
I've never done it personally, but I did find this [link](https://blogs.windows.com/buildingapps/2014/12/17/bring-your-windows-phone-silverlight-apps-to-windows-runtime-xaml-prepare-for-universal-app-development-in-windows-10/) that seems to have lots of information on the process.
