### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by wtmw** [Microsoft/winsdkfb#150]
I use VS 2015 community.
The error is c1xx : fatal error C1083: Cannot open source file: 'C:\Users\Tim\Downloads\winsdkfb-master\winsdkfb-master\samples\SDKCppUnit\SDKCppUnit.Shared\Generated\APIResult.cpp': No such file or directory

When I open the folder, I can find  APIResult.h but APIResult.cpp not there

**Comment by adiviness** [comment]
What I believe is happening is that we have many files that are generated at compile time and if you are building for both windows and windows phone at the same time they may conflict when trying to generate or read from these files. Try changing the target platform you're building for to x64 (so it only builds for desktop and not phone) and build the solution. You should then be able to build for anything else because the files will have already been generated. Let me know if that fixes the problem.

**Comment by wtmw** [comment]
There are seven sub projects in the big project.
They are 
FBWinPhoneStoreCppTests
FBWinStoreCppTests
FBWinStoreCsTests
SDKCppUnit.Windows
SDKCppUnit.WindowsPhone
winsdkfb.Windows
winsdkfb.WindowsPhone

If I choose SDKCppUnit.Windows or SDKCppUnit.WindowsPhone to bulid and deploy, the problem(no APIResult.cpp in the directory) will appear.

Other five sub projects can be compiled well.

please look at this screenshot http://socialmediadata.azurewebsites.net/img/compile.png

Thanks

**Comment by adiviness** [comment]
Do you get an error when you run `/samples/SDKCppUnit/SDKCppUnit.Shared/codegen.cmd` with an msbuild cmd prompt (or some cmd prompt that has `TextTransform.exe` in your path)?

**Comment by wtmw** [comment]
Sorry, I can't understand you very clearly.
If I run codegen.cmd in /samples/SDKCppUnit/SDKCppUnit.Shared path, I got the following message:
The system cannot find the batch label specified - GenFile

Is this what you want me to do?

**Comment by adiviness** [comment]
I think so. So I'm not sure yet why this is a problem, but it seems to only manifest when the repo is downloaded via the zip file on github vs. cloning with git. It looks like the newlines are different between the `codegen.cmd` files for each method of getting the repo. My suggestion would be to clone the repo with git and see if the problem persists.

**Comment by khouzam** [comment]
Git handles line endings differently on Windows than on Linux. When you clone on windows the proper line endings are set, but for a zip file, the line endings cannot be changed based on where the file is unzipped.

Unfortunately, there's not much we can do about this. This is how GitHub creates the zip file.

**Comment by khouzam** [comment]
We've just started hitting the issue ourselves on our build server. There seems to be something strange about this even though the file itself hasn't changed.

**Comment by khouzam** [comment]
Hi @wtmw 

I've submitted a work-around for the issue, commit 44cfa78ae284d3f6604f0195e9c373b8b7ec8e9f should fix the issue. I've validated that it works with the .zip file and our build server.
