### ISSUE TITLE
nuget wont install on VS 15 preview

### ISSUE THREAD

**Issue by tggmbi** [Microsoft/winsdkfb#154]
getting:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not load file or assembly 'Microsoft.VisualStudio.ProjectSystem.V14Only, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.			0

**Comment by khouzam** [comment]
Thanks, we'll pass it on to the Visual Studio team.
