### ISSUE TITLE
Fix to succeed Microsoft "STARTS" tests

### ISSUE THREAD

**Issue by AlanGusLive** [Microsoft/winsdkfb#157]
Hi,

To succeed Microsoft "STARTS" tests ([http://aka.ms/startsqualitybar](http://aka.ms/startsqualitybar)) for my UWP application, I fixed winsdkfb.

In the Windows Store STARTS Review Results of my game, I received this issue:
Blank message display during offline log in. When the application is offline and the user attempts to log in, the application should warn the user of the offline status.

Test Case: 02.01
Steps to Reproduce:
1. Launch the application.
2. Select the settings icon.
3. Select the Facebook icon.
4. Turn airplane mode on.
5. Attempt to log in with Facebook.
6. Notice the blank white screen.
Note: This also occurs when logging into Twitter.

I will send you today a pull request to fix this issue. I had the same problem with Twitter because as there is NO SDK for Twitter and UWP, I wrote it by using winsdkfb. Yes, I replaced Facebook by Twitter, changed a lot of things, added HMACSHA1 (Keyed-Hash Message Authentication Code) to sign the message and it’s not magic, it works. I can login/logoff with Twitter and send a Tweet even in chiness :-)

If you want to see how I have integrated Facebook/Twitter in my fully free reflexion game available for Windows 10 (PC/Mobile) since few days, you can download it in the store. The name is "[**Fruity Mix Free**](https://www.microsoft.com/store/apps/9nblggh625sc)" and the link is https://www.microsoft.com/store/apps/9nblggh625sc

I am starting the Xbox One version of my game, I hope winsdkfb works with Xbox One.

Regards,
AlanGusLive ([**Fruity Mix Free**](https://www.microsoft.com/store/apps/9nblggh625sc))

**Comment by adiviness** [comment]
Associated pull request has been merged, thanks!
