### ISSUE TITLE
Unable to Post Videos if Location is mentioned in parameters..

### ISSUE THREAD

**Issue by abhinovpankaj** [Microsoft/winsdkfb#159]
Unable to Post Videos if Location is mentioned in parameters..

Also getting Exception "Cannot perform run-time binding on a null reference"
 if only Parameters have title and description mentioned.

                   parameters.source = new FacebookMediaObject { ContentType = "video/" + extn.Replace(".",""), FileName = fileName }.SetValue(File.ReadAllBytes(filePath));
                    parameters.title = fileName;
                    
                    parameters.description = "Added by Point5Nyble WinAPP";
                    
                    dynamic result =  await fb.Post("/me/videos", parameters);

**Comment by adiviness** [comment]
This does not appear to be our API, what version of the sdk are you using?

**Comment by abhinovpankaj** [comment]
I have used Facebook 7.0.6 version.
Downloaded directly from nuget gallery.

**Comment by adiviness** [comment]
That does not sound like this project, we do not have a 7.0.6 version. [This](https://www.nuget.org/packages/winsdkfb/) is our nuget package. I think you may be actually using [this](https://github.com/facebook-csharp-sdk/facebook-csharp-sdk) sdk instead. If that is the case, I would recommend you update to this sdk.
