### ISSUE TITLE
Unable to LogOut using WebAuth

### ISSUE THREAD

**Issue by vladcristea** [Microsoft/winsdkfb#161]
Hi,
 In my app I'm using winsdkfb and everything works fine when I log in using sessionloginbehavior.webAuth. The problem is when I'm trying to implement log out, because the cookies  are not deleted and the same account will be saved for the next login. How can I force a log out, so the next user to enter the credentials again? I was trying this:
   var myFilter = new Windows.Web.Http.Filters.HttpBaseProtocolFilter();
            var cookieManager = myFilter.CookieManager;
            var myCookieJar = cookieManager.GetCookies(new Uri("https://www.facebook.com"));
            var myCookieJar1 = cookieManager.GetCookies(new Uri("https://m.facebook.com"));
            foreach (var cookie in myCookieJar)
            {
                cookieManager.DeleteCookie(cookie);
            }

but without any success. All the time the Jars are empty. LogOutAsync() will unauthorize the user, but not delete the credentials.

Thank you very much

**Comment by khouzam** [comment]
Hi @vladcristea 

This issue should have been addressed with the following pull request: https://github.com/Microsoft/winsdkfb/pull/119

The code is still in our develop branch, can you try that until it reaches master.

Thanks

**Comment by khouzam** [comment]
Sorry, I had missed the fact that you are using WebAuth and not WebView. The WebAuth infrastructure is targeted at a single identity scenario. Similarly to login in through the Facebook app, you want to leverage the current user and not have to keep entering a password. If you want to easily logout, then I would suggest that you use WebView instead which allows for the user to logout.

**Comment by vladcristea** [comment]
@khouzam Thank you very much for the clarification. It is very helpful. I have a problem using the web view: on facebook app there are some redirects uri and all the time I get the error message "not logged in..." I don't have access to change that. Can I specify somehow the redirect uri from code?

**Comment by khouzam** [comment]
If you look at the code in our develop branch, the ability to specify a different redirect uri has been added. Hopefully this will unblock you.

**Comment by alakshmi1030** [comment]
Please reopen if you are still having a problem with this.
