### ISSUE TITLE
Processor architecture AnyCPU - forced to choose x86 or x64

### ISSUE THREAD

**Issue by MarketMole** [Microsoft/winsdkfb#164]
I have successfully included the github project within my Windows store project: winsdkfb.Windows.
My project started out as AnyCPU, both it and 3 supporting libraries. However, in order to build the appbundle for store submission I must choose either x86 (win32 for the winsdkfb.Windows project) or x64 across the board. No longer will AnyCPU work.

Is this by design? And as such must I submit two separate appbundles, one per cpu architecture?

If I were to add the winsdkfb.Windows via nuget, would this change anything? (I surmise not - but wanted to be sure).

I'll be adding the Windows.Phone version of winsdkfb to the project soon, but I realize that ARM is a hard requirement for that platform, (win32/x86 to run in the emulator, but ARM to run on a device). Yet even for that setup, my AnyCPU supporting libraries must now be hard selected to either x86 or ARM -- correct? To simplify, AnyCPU is no longer an option once winsdkfb is added to your project, true statement?

**Comment by khouzam** [comment]
Yes, this is now a requirement because the SDK is written in C++ and not C#.

C++ doesn't support the AnyCPU configuration that C# can support. With Windows 10, C# will also compile down to native code and you will need to submit a bundle for every architecture to submit something to the store.

**Comment by MarketMole** [comment]
Thanks for your confirmation. Rather confounds the construction and deployment a bit... But no choice that. Ah well, it's always three steps forward, two steps back with Microsoft. (Or now with winphone, one step forward, end-of-the-line, go learn Android.)
