### ISSUE TITLE
Is there a method to add app's Insight ?

### ISSUE THREAD

**Issue by sunilsunny565** [Microsoft/winsdkfb#168]
When people install or engage with your app, you'll see this data reflected in your app's Insights dashboard.Android and IOS Facebook SDK's provide this functionality, simply need to initialize this "AppEventsLogger" .Is there something similar in this SDK. Will be a great help if you add this too..

**Comment by adiviness** [comment]
We don't currently have any telemetry features built into the sdk. Are you referring to the same logging as #72?

**Comment by sunilsunny565** [comment]
Yes , I am referring to the same logging.
tnx.

**Comment by adiviness** [comment]
With that being the case I'm going to go ahead and close this issue so we don't have duplicates.
