### ISSUE TITLE
Clicks go through UI ('X' to close Login/Share/etc-popup)

### ISSUE THREAD

**Issue by Whyser** [Microsoft/winsdkfb#170]
As the title says (so far tried on Windows Store (desktop)). 

When, for example, the login dialog is shown and a user presses the X-button to close the popup, the click will propagate to whatever is beneath the popup. So if I have a button beneath the 'X' it will both click the X and my button below. This does not happen if I press anything inside the actual window though.

I would prefer not to "manually" have to disable the rest of my UI because of this. :/

Thanks!

(A little related to: https://github.com/Microsoft/winsdkfb/issues/125)

**Comment by adiviness** [comment]
I am unable to repro this, as far as I can tell no clicks will register with the background elements as long as the dialog is open. I am able to click the 'x' button to close the popup while it is being displayed in front of another button and the other button will not register a click. What version of windows are you seeing this on? what version of the sdk are you using? Are you able to provide a sample to reproduce the problem?

**Comment by Whyser** [comment]
I'm using the develop branch. I realize I was about vague when I said
"buttons", because they are not buttons in the way you think. The
click-through goes through the X-button and triggers Unitys click events
(on various Unity UI objects), meanwhile the pop-up itself doesn't do that.
I will try attach a repro-project later today.

**Comment by adiviness** [comment]
Feel free to reopen this issue once you have a repro project available.

**Comment by ByronMayne** [comment]
This is not caused by winsdkfb. In Unity you have to disable on it's page before you show Facebook. Take a look at `AppCallbacks.UnitySetInput(bool enabled)`. it's up to you to toggle this.
