### ISSUE TITLE
Posting Photo with Accompanying Text

### ISSUE THREAD

**Issue by ferretnt** [Microsoft/winsdkfb#175]
The samples included show how to post a photo, and how to post a text status update. Is there any way to use the feed dialog to show a (prepopulated) photo alongside a text field for the user to enter text?

**Comment by adiviness** [comment]
The `PropertySet` that is passed when you call `FBSession::ShowFeedDialogAsync` can contain a "picture" key along with the URL of the image you want attached to the post. More information can be found at https://developers.facebook.com/docs/sharing/reference/feed-dialog/v2.6

**Comment by ferretnt** [comment]
Great - thanks for the quick response. To clarify, can URL be a file:// URL (assuming that the picture is new content the user has just generated in-app, and we haven't posted it to the web yet?)

**Comment by alakshmi1030** [comment]
No, the URL from the feed dialog reference is talking about a web URL for the image you are trying to show. The Facebook Graph API has separate endpoints for uploading a photo ("/<userID>/photos") vs. uploading to the feed/timeline ("/<userID>/feed"). You can try using the caption parameter when uploading a photo: https://developers.facebook.com/docs/graph-api/reference/user/photos/

**Comment by ferretnt** [comment]
"caption" seems to work. Thanks!
