### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by snowman745** [Microsoft/winsdkfb#180]
After downloading the latest zip file today, i see the build error that was reported here:
https://github.com/Microsoft/winsdkfb/issues/150

Cannot open source file: 'G:\winsdkfb-master\samples\SDKCppUnit\SDKCppUnit.Shared\Generated\APIResult.cpp': No such file or directory	SDKCppUnit.Windows	G:\winsdkfb-master\samples\SDKCppUnit\SDKCppUnit.Windows\c1xx\

This happens even if I switch to x64 but only happens building from the solution level.

I can build individual projects (windows 8.1 and windows phone 8.1)

**Comment by adiviness** [comment]
When you downloaded the zip file, what branch was it based on? The fix for #150 hasn't made its way to our `master` branch quite yet.

**Comment by snowman745** [comment]
Yes, I just downloaded the zip from the main page. Thanks.

**Comment by adiviness** [comment]
If you clone the project instead of downloading the zip file then you can use `master` just fine because the line endings will be correct. If you need to use the zip file then download the one for the `develop` branch.
