### ISSUE TITLE
Add AppInviteDialog feature

### ISSUE THREAD

**Issue by rozele** [Microsoft/winsdkfb#188]
Looking for something similar to https://developers.facebook.com/docs/reference/android/current/class/AppInviteDialog/.

Currently, the `ShowRequestDialogAsync` API does not work for regular Facebook enabled apps (only games) and the `ShowSendDialogAsync` API is not quite adequate either.

**Comment by alakshmi1030** [comment]
Looking at this reference documentation it doesn't seem like the AppInviteDialog endpoint URL is public so we can't encapsulate it in our SDK. Do you have a link to documentation where they reference a public endpoint?

**Comment by adiviness** [comment]
This appears to be a limitation of the public graph APIs and not our SDK, I don't believe that there is much we can do to change this.
