### ISSUE TITLE
Friend List

### ISSUE THREAD

**Issue by anirudhnegi** [Microsoft/winsdkfb#189]
Can we get the friend list of the login user using this SDK. Needs someones guidance.
Thanks & Regards
Anirudh Negi

**Comment by alakshmi1030** [comment]
Hello Anirudh - you can grab the friend list of the user using this Graph API endpoint:
https://developers.facebook.com/docs/graph-api/reference/user/friends/

Documentation on how to structure a graph request using our SDK is available on our docs site:
http://microsoft.github.io/winsdkfb

Note that you can only get the list of friends who are also using your app. So if you are logged in and 10 of your friends have also logged in and accepted the app's permissions, viewing your friend list will only show those 10 people and not your entire friend list.

**Comment by anirudhnegi** [comment]
I really appreciate your response.Thank you for the information.
