### ISSUE TITLE
SDK crashes in some cases when the wrong password is inserted

### ISSUE THREAD

**Issue by avindak** [Microsoft/winsdkfb#192]
When a user enters the wrong password the following exception is raised:
System.Exception: The specified account does not exist.
The error happens on some devices in some cases.

**Comment by adiviness** [comment]
I need some more information if you don't mind. What version of the sdk are you using? Is it the nuget package or are you cloning the project? If you cloned the project what branch? What login method are you calling? What devices and Windows version are you using?

**Comment by avindak** [comment]
No clones or anything like that. We use the June 21st NuGet package https://www.nuget.org/packages/winsdkfb/0.10.20160621.3
We use ActivateApp() method on many devices and versions of Windows 10 as a UWP app.

**Comment by adiviness** [comment]
Calling `FBSDKAppEvents::ActivateApp` does seem to throw an exception, but it doesn't spawn a dialog for a user to stick in a password. Are you calling `FBSession::LoginAsync` to log in?

**Comment by avindak** [comment]
All we do is call the following:
FBSession.ActiveSession.FBAppId = xxx
FBSession.ActiveSession.WinAppId = xxx
FBSDKAppEvents.ActivateApp();

**Comment by adiviness** [comment]
We recently released a new nuget package that should address this problem, can you try with that and let me know if you're still having problems? You will likely need to add a line like `FBSDKAppEvents.UseSimulator = true;` before calling `FBSDKAppEvents.ActivateApp`.

**Comment by alakshmi1030** [comment]
Please reopen if you are still experiencing this issue.

**Comment by avindak** [comment]
The new version works on stages and the problem was not reproduced
