### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by Bodaciouslycrazy** [Microsoft/winsdkfb#194]
Hello! I'm trying to install this package to run on a winforms application, but I keep getting this message...

"Could not install package 'winsdkfb 0.10.20160621.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

I'm not sure what I am doing wrong. Can you help?

**Comment by khouzam** [comment]
Hi @Bodaciouslycrazy 

The SDK is made to target Windows 8.1 and Windows 10 universal applications, it will not target winforms. you might want to take a look at https://hackerapp.com/net/

**Comment by Bodaciouslycrazy** [comment]
I have already tried to use that before, but I can't find any documentation of it. It's a bit frustrating...
