### ISSUE TITLE
Unable to receive response

### ISSUE THREAD

**Issue by wapacro** [Microsoft/winsdkfb#198]
I'm always getting the error "Unable to receive response" no matter on what device I try.
![fb](https://cloud.githubusercontent.com/assets/11590853/17274057/aefbe206-56ce-11e6-9464-caf64b9c33d2.PNG)

It's a Windows 10 UWP application.

**Comment by adiviness** [comment]
What you have there looks correct to me. That error message is probably coming from `FBSingleValue`, when it makes an HTTP request that receives an abnormal response it returns that error message. It's a known issue that the error messages aren't as helpful as they could be, if you are able to inspect the actual HTTP response by either using a tool like Fiddler or setting a breakpoint in `FBClient::TryReceiveHttpResponse` that would be a good first step in diagnosing the problem. Are you able to input login information in the dialog that pops up?

**Comment by wapacro** [comment]
Oh, snap! Found the problem using the VS 2015 network debugger. I destroyed the already existing session on facebook.com without logging out in my app. winsdkfb tried to reopen the session which was already closed, causing a HTTP 400 error.

![traffic](https://cloud.githubusercontent.com/assets/11590853/17276581/ade7413a-572d-11e6-8f7e-4aab182871e2.PNG)
