### ISSUE TITLE
The ShowRequestsDialog() method doesn't return in a UWP app

### ISSUE THREAD

**Issue by qmatteoq** [Microsoft/winsdkfb#20]
I'm adding the Facebook SDK in a Universal Windows app based on SDK 10069 and running on Windows 10 10166.
Everything is working fine (login, Graph API, etc.). However, when I call the ShowRequestsDialog() method, it never returns.
Here is the code I'm using:

```csharp
        private async void OnPostClicked(object sender, RoutedEventArgs e)
        {
            if (session.LoggedIn)
            {
                PropertySet parameters = new PropertySet();
                parameters.Add("message", "Try my application!");
                FBResult result = await session.ShowRequestsDialog(parameters);
                Debug.WriteLine(result.Object);
            }
        }
```
The request windows is correctly displayed and I'm able to successfully send invites. However, when I press the "Done" button and the popup is dismissed, the method doesn't return. Consequently, the line that should print in the Ouput Window the value of result.Object is never called.

**Comment by ekalbredneb** [comment]
Sorry for the delay, Matteo!  This was an embarrassing little bug due to a typo or an errant cut/paste along the way that left a semicolon at the end of the while loop that was waiting for the requests dialog to complete.  I merged the fix this morning, please pick up the change and try it out.
