### ISSUE TITLE
title and description not showing up

### ISSUE THREAD

**Issue by FredStrasser** [Microsoft/winsdkfb#200]
I can post on my Facebook Timeline, but the "title" and "description" strings are not included in my postings. As you see in the attached picture, the post does not include the title and description from the propertyset. The Facebook page title and page description is displayed instead.

Is this issue caused because the link is targeting a facebook page? How can i post a link to my Facebook page with a title and description included that i pass from my app?

I am using this code to post:
PropertySet parameters = new PropertySet();
parameters.Add("title", "This is the title.");
parameters.Add("link", "https://www.facebook.com/myfacebookpage");
parameters.Add("description", "This is the description");
FBResult fbresult = await _session.ShowFeedDialogAsync(parameters);

![facebookissue](https://cloud.githubusercontent.com/assets/21063322/17706802/c285075a-63dd-11e6-86bd-89030745eb16.png)

**Comment by alakshmi1030** [comment]
I'm seeing the following - which version of the SDK are you using? Are you using the Nuget package or the source from Github?

![fbpage](https://cloud.githubusercontent.com/assets/1602674/18013680/141c9932-6b74-11e6-902a-71e1b4789335.PNG)

**Comment by FredStrasser** [comment]
I am using Nuget Package winsdkfb (0.11.20160720.1)

However, i have already created a Website for my app, and with this URL as link Parameter everything works fine. What URL have you used in your test? I have read in a Facebook Forum that Facebook handles the post different when the URL is a valid Facebook page. Sorry i can't find this discussion anymore, so i can't link it here.

**Comment by FredStrasser** [comment]
Found this that seems to be the same issue:
https://developers.facebook.com/bugs/1543859162514546/

So this is by design. Would be nice if Facebook would provide a documentation about this behavior.
