### ISSUE TITLE
is this project still under active development?

### ISSUE THREAD

**Issue by HanAnonymous** [Microsoft/winsdkfb#201]
I'm very skeptical to use this library in my UWP project.. the documentation is not updated..

                var factory = new FBJsonClassFactory(s =>
                {
                    return JsonConvert.DeserializeObject<FBReturnObject>(s);
                });

I get FBReturnObject doesn't exist in current context error -_-

**Comment by adiviness** [comment]
The documentation should very much up to date, I  recently updated all of the code samples in it. At the top of the graph api page of the documentation there is a section titled "A Helper Class" which explains what `FBReturnObject` is.

**Comment by HanAnonymous** [comment]
thanks bro! you just saved my day
