### ISSUE TITLE
In Windows Phone, LoginAsync not showing the login dialog box when the facebook NOT logged in to website(m.facebook.com) 

### ISSUE THREAD

**Issue by nidheesh-cl** [Microsoft/winsdkfb#202]
Hi,

I have a new issue which was not happening earlier. I logout of m.facebook.com site(or if the facebook website session expires). I then tried to login to my UWP application which is integrated to do FB login using winsdkfb. When it tries to do FBSession.LoginAsync method, it is failing and FBError is saying OAuthException. But earlier when this happens application automatically show the login page for user to enter the fb credentials. but not it is throwing the error rather than showing the dialog box of login.

Thanks
Nidheesh

**Comment by adiviness** [comment]
What version of windows phone and winsdkfb are you using? Are you calling the default `FBSession::LoginAsync` method or are you specifying a specific `SessionLoginBehavior`?

**Comment by nidheesh-cl** [comment]
Windows 10 Mobile(Lumia 1520 upgraded to Windows 10). Winsdkfb version is 0.9.20160315.6.

Just noticed that this issue is not there when the app is built in Release mode. It happened when it is built in debug mode.

**Comment by adiviness** [comment]
You're using a nuget package that is 2 releases behind, I would suggest updating to the latest package and seeing if the problem persists. There's a bunch of bug fixes that have been resolved since the 0.9 package was released.

**Comment by nidheesh-cl** [comment]
Thank you very much. This worked after upgrading to 0.11.20160720.1
