### ISSUE TITLE
VS Nuget Manager: package does not contain any assembly references ...

### ISSUE THREAD

**Issue by HoneyWheat** [Microsoft/winsdkfb#203]
Error: Could not install package 'winsdkfb 0.11.20160720.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I tried this from .NET 3.5 up to 4.6.1

**Comment by khouzam** [comment]
This SDK targets Windows Universal apps for Windows Store and Phone but not desktop applications.
