### ISSUE TITLE
WinRT information: The application called an interface that was marshalled for a different thread.

### ISSUE THREAD

**Issue by sfolador** [Microsoft/winsdkfb#207]
Hi, 

I'm developing a Windows Phone 8.1 application. I followed your official guide but if I do the following:

             
               FBSession sess = FBSession.ActiveSession;
                // Add permissions required by the app
                List<String> permissionList = new List<String>();
                permissionList.Add("public_profile");

                FBPermissions permissions = new FBPermissions(permissionList);

                // Login to Facebook
                FBResult result = await sess.LoginAsync(permissions);

                if (result.Succeeded)
                {
                    //Login successful
                    if (sess.LoggedIn)
                    {
                        // Get current user
                        FBUser user = sess.User;
                        Debug.WriteLine("asdhaksjdakjsdhkads");
                        // Set profile pic

                    }

                }
                else
                {

                    Debug.WriteLine("12387");
                    //Login failed
                }

I always get the Exception: 

**WinRT information: The application called an interface that was marshalled for a different thread.**

the Exception is thrown at: _winsdkfb.FBSession.LoginAsync(FBPermissions Permissions)_

I tried also to wrap a dispatcher around but it doesn't solve anything. Have you got any advice?

**Comment by adiviness** [comment]
What version of the sdk are you using (and is it nuget or git clone)?

**Comment by khouzam** [comment]
Are you creating a Silverlight or a Universal Windows 8.1 application? The SDK will not work with Silverlight applications.

**Comment by alakshmi1030** [comment]
Please reopen if the feedback did not address the issue
