### ISSUE TITLE
Windows Phone 8.1 WebAuth behavior doesn't works because NotImplementedException in AuthenticateAsync

### ISSUE THREAD

**Issue by MarcorOnline** [Microsoft/winsdkfb#209]
AuthenticateAsync does not works on Windows Phone 8.1 device.
It works only on Windows 10 Mobile device.
You have to replace it with AuthenticateAndContinue and the user have to override OnActivated in App.xaml.cs and call a method on Session to complete the login process

**Comment by alakshmi1030** [comment]
This is related to a previously closed issue #104 - for Windows Phone 8.1 you can't use WebAuth to login, only WebView.
