### ISSUE TITLE
Add the Async() suffix to all the asynchronous methods

### ISSUE THREAD

**Issue by qmatteoq** [Microsoft/winsdkfb#21]
The naming convention used by the Windows Runtime APIs is to mark asynchronous methods by adding the Async() suffix at the end (like GetGeopositionAsync(), PostAsync(), etc.).
Currently, some methods of the Facebook SDK are following this naming convention (like LoginAsync(), while some others not (like ShowFeedDialog(), ShowRequestsDialog(), Get(), Post(), etc.).

It would be great to have a common naming convention across all the APIs.

**Comment by adiviness** [comment]
As of commit 54bdce9f95eea2f7e1ec54b62ac7cf9ca3cb34ed all public async methods should have the Async suffix.
