### ISSUE TITLE
User's albums and pictures?

### ISSUE THREAD

**Issue by assassin316** [Microsoft/winsdkfb#210]
Will the Facebook service support fetching a user's albums and pcitures?

**Comment by adiviness** [comment]
You can use this sdk to make Facebook Graph API calls as described in our documentation [here](https://microsoft.github.io/winsdkfb/graph/). The graph API documentation for photos can be found [here](https://developers.facebook.com/docs/graph-api/reference/photo).

**Comment by assassin316** [comment]
So I followed the Graph Api, and I get an web response error, is this the correct way? In this case, I'm simply trying to get the user's albums:

    `FBSession sess = FBSession.ActiveSession;

	// If the user is logged in
	if (sess.LoggedIn)
	{
		// Get current user
		FBUser user = sess.User;
		
		PropertySet parameters = new PropertySet();
		
		// Set Graph api path
		string path = "/" + user.Id + "/albums/";
		
		var factory = new FBJsonClassFactory(s =>
		{
			return JsonConvert.DeserializeObject<FBReturnObject>(s);
		});
		
		var singleValue = new FBSingleValue(path, parameters, factory);
		var result = await singleValue.PostAsync();
		
		if (result.Succeeded)
		{
			var response = result.Object as FBReturnObject;
		}
		else
		{
			// Failed
		}
	}`

**Comment by adiviness** [comment]
It's fairly close. Are you setting the app IDs on `FBSession` and calling `FBSession::LoginAsync`? According to the documentation at https://developers.facebook.com/docs/graph-api/reference/user/albums/ you should be using a GET request instead of a POST request. Also, `FBSingleValue` is for graph calls that return a single value, but since the endpoint you're trying to use can return multiple values you should be using `FBPaginatedArray` instead.

**Comment by assassin316** [comment]
Ok, so it's working! I see my albums in the json string returned from the callback in the factory object. One last question, when the web query completes, "result.Object" is of type COMObject and doesn't cast to FBReturnObject. Is there another way to cast that result to a .Net type ??

Here is the updated code:

    if (sess.LoggedIn)
    {
		// Get current user
		FBUser user = sess.User;

		PropertySet parameters = new PropertySet();

		// Set Graph api path
		string path = "/" + user.Id + "/albums";

		var factory = new FBJsonClassFactory(s =>
		{
			return JsonConvert.DeserializeObject<FBReturnObject>(s);
		});

		var arr = new FBPaginatedArray(path, parameters, factory);
		var result = await arr.FirstAsync();

		if (result.Succeeded)
		{
			var response = result.Object as FBReturnObject;
		}
		else
		{
			// GET failed
		}
	}

**Comment by adiviness** [comment]
It is the `FBJsonClassFactory` that does the conversion, it takes the JSON response text and passes it into the lambda function you created it with. The result of the lambda function is the `result.Object`. So you can do whatever you want with the JSON, you just have to create a class and tell the factory how to transform the JSON text into an instance of that class.

**Comment by assassin316** [comment]
Ok thanks, I had thought it was that. I created my class and deserialize it as such:

	public class FacebookAlbum
	{
		[JsonProperty(PropertyName = "created_time")]
		public string CreatedTime { get; set; }

		[JsonProperty(PropertyName = "name")]
		public string Name { get; set; }

		[JsonProperty(PropertyName = "id")]
		public string Id { get; set; }
	}
	
	.
	.
	.
	
	
	// Set Graph api path
	string path = "/" + user.Id + "/albums";

	var factory = new FBJsonClassFactory(s =>
	{
		return JsonConvert.DeserializeObject<FacebookAlbum>(s);
	});

	var arr = new FBPaginatedArray(path, parameters, factory);
	var result = await arr.FirstAsync();

	if (result.Succeeded)
	{
		var response = result.Object as FacebookAlbum;
	}
	else
	{
		// GET failed
	}

Still getting a COM object but I'll continue investigating and report back when I figure out why.

**Comment by adiviness** [comment]
So it turns out that after calling `FBPaginatedArray::FirstAsync`, the `FBResult` object will have an `IVectorView` of the object created by the factory and not a single instance of the object. I think what you'll need to cast it to is `IReadOnlyList<FacebookAlbum>`, but I'm not super familiar with C#.

**Comment by assassin316** [comment]
Ah yes, it explains why the deserialization code executes multiple times and the result only once, obviously  :)   I'll try it. Thanks again!
