### ISSUE TITLE
Is it available to receive instant messages?

### ISSUE THREAD

**Issue by andrshevch** [Microsoft/winsdkfb#227]
Does sdk provide such mechanism?

**Comment by adiviness** [comment]
I don't believe so, unless there is a graph api that I'm unaware of that provides this. But even then you'd have to manually poll the api instead of the sdk providing some sort of event for your app to listen for.

**Comment by andrshevch** [comment]
where can i find any documentation to do the manual requests?

**Comment by adiviness** [comment]
[Here](https://developers.facebook.com/docs/graph-api) is the facebook graph api documentation and [here](http://microsoft.github.io/winsdkfb) is the winsdkfb documentation, as found in our readme.
