### ISSUE TITLE
"Not logged in, please log in to continue"

### ISSUE THREAD

**Issue by zoxin** [Microsoft/winsdkfb#228]
when I showed a feed dialog, it always popup a dialog with the text "Not logged in, please log in to continue".   Also there is a "Log in" button in the dialog. If I click the button, it will popup again...
So, how can i fix it?  thanks!!

**Comment by zoxin** [comment]
it only occured in desktop with login type SessionLoginBehavior::WebAuth

**Comment by adiviness** [comment]
I can't repro this behavior. What version of the sdk are you using? What platform are you experiencing this on?

**Comment by adiviness** [comment]
If you're still experiencing this problem please reopen the issue.
