### ISSUE TITLE
Installing NuGet package 0.12.2016.1020.4 results in startup error

### ISSUE THREAD

**Issue by kellylawson** [Microsoft/winsdkfb#229]
Hi,

I've tried using the winsdkfb package by adding it to my UWP app through NuGet.  After adding it and implementing the basic login code, when I try to start up to test my app no longer runs.  It throws a TypeLoadException with the following detail:

Requested Windows Runtime type 'winsdkfb.winsdkfb_uwp_XamlTypeInfo.XamlMetaDataProvider' is not registered.

I can see the winsdkfb reference in my project, I'm wondering if this is a good package or if I'm doing something wrong?

Thanks for your help.

**Comment by adiviness** [comment]
Can you try a full rebuild and see if the problem persists?

**Comment by kellylawson** [comment]
Oh, how embarrassing.  That worked - sorry to bother.  I appreciate the help.

**Comment by FrancoisM** [comment]
Nothing embarrassing here.
I'm having the same issue and a full rebuilt is not obvious (why would it be?)
