### ISSUE TITLE
FBSession::Expires is always 0?

### ISSUE THREAD

**Issue by TedHoward** [Microsoft/winsdkfb#23]
At least when I check after FBSession::LoginAsync it seems to be. However FBSession::AccessTokenData::ExpirationDate is valid, which also has me wondering why FBSession::Expires exists - just have devs get it from AccessTokenData.

**Comment by ekalbredneb** [comment]
Thanks for pointing this out.  You're correct, FBSession::Expires is vestigial, and should be removed.  Use the value in AccessTokenData.

**Comment by TedHoward** [comment]
np
Happy to improve things for everyone. At some point, I may have a PR for
your team. Right now I'm just getting the basics of FB integration in place
in our game.

-ted

**Comment by adiviness** [comment]
b53532fb0ea7a5ffb7488ac1dad2ea626607837e removes FBSession::Expires from the code base.
