### ISSUE TITLE
link preview doesn't look great in feed dialog

### ISSUE THREAD

**Issue by Hanzalah-Adalan** [Microsoft/winsdkfb#234]
there's no problem when the window is in wide mode... but when user resize the window size <=500, the link preview will be cropped in an undesired way.. can you guys make that embedded web browser a little adaptive to various screen size...

here's how it appears in my app..

![cropped](https://cloud.githubusercontent.com/assets/9501081/22861552/a50f50b6-f156-11e6-85db-b8ece0b7f1f8.PNG)

but strangely.. the Send Dialog however can wrap the content nicely

![okay](https://cloud.githubusercontent.com/assets/9501081/22861701/c9278334-f15a-11e6-8849-c3c41ef5a00b.PNG)

**Comment by yodurr** [comment]
This content comes from Facebook.  We've notified them of this issue.  Thanks.

**Comment by Hanzalah-Adalan** [comment]
thank you sir, hope they will fix that soon
