### ISSUE TITLE
FBSession::Login UI is full-screen on Win8?

### ISSUE THREAD

**Issue by TedHoward** [Microsoft/winsdkfb#24]
When our app launches FBSession::Login in the hosted WebView, it is a full-screen dialog for just the simple login UI. Seems excessive. Maybe it's something I can control somehow within xaml and so it just needs some documentation tips.

fyi
Our app is a pure C++ game. I just switched it to using SwapChainBackgroundPanel so that, among other things, we could use this new FB SDK. So our app does nothing in xaml except create 1 element.

**Comment by ekalbredneb** [comment]
The dialogs in the SDK are all set to cover the entire app window, yes.  This is expected behavior on the phone, though perhaps as you mention it's not the ideal experience on the desktop.  It'll require some work in the SDK code itself, most likely, to change.

**Comment by TedHoward** [comment]
Yep. My first thought was "Well that would be the right thing on a phone."
If I happen to figure out a good scheme, I'll share a PR or snippet.

-ted

**Comment by TedHoward** [comment]
Does the new emphasis on UWP change this? Or iow, what *exactly* does this look like on the Xbox One? If it's ugly on Win10, it'll be ugly on Win10/XboxOne.

I'm local (Seattle) and more than happy to help make this right.

**Comment by adiviness** [comment]
To be honest, I haven't seen the sdk running on an xbox. But I would imagine that it would be similar to what happens on desktop. I don't believe the sizing behavior changes if the UWP version of the sdk is used, we are certainly welcoming of any pull requests to fix the issue.

**Comment by adiviness** [comment]
As of 80a2eae3883495c1e17244957d3a23c1f45ea18c dialogs no longer take up the full screen on desktop apps. This change has made it to both the `develop` and `master` branch.
