### ISSUE TITLE
Does SDK support single sign on ?

### ISSUE THREAD

**Issue by narcis96** [Microsoft/winsdkfb#241]
After running my app and try to log in, there is any way that my app use credentials from facebook app where I am already logged in ?

**Comment by adiviness** [comment]
If your app is running on Windows 10, our `LoginAsync` method will attempt to get an access token from the facebook app. But right now this is broken, see #238. I think we get SSO tokens through the other login options but I don't remember definitively anymore. You can check by calling `LoginAsync` with different `SessionLoginBehavior` options and running the token returned through the facebook [access token tool](https://developers.facebook.com/tools/accesstoken/).
