### ISSUE TITLE
Why can not i install from nuget?

### ISSUE THREAD

**Issue by ngochoaitn** [Microsoft/winsdkfb#247]
I search winsdkfb from Nuget but I can not install it!
Error message:
Could not install package 'winsdkfb 0.13.20170131.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by khouzam** [comment]
Hi @ngochoaitn,

It looks like you're not targeting a Windows 10 Universal project, but a .Net desktop (WPF, WinForms) project.

The project support Windows 10 universal applications only.
