### ISSUE TITLE
HOW TO POST,GET PLAYER SCORE TO FACEBOOK?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [Microsoft/winsdkfb#248]
I'm create a game have Login with Facebook to store player score. How to post and get player score to Facebook?

**Comment by adiviness** [comment]
Our documentation on how to interact with Facebook's Graph API can be found here: https://microsoft.github.io/winsdkfb/graph/

Facebook's documentation on the Graph API can be found at https://developers.facebook.com/docs/graph-api

You might want to use the [Feed Dialog](https://microsoft.github.io/winsdkfb/dialogs/#0) to post to the player's feed.
