### ISSUE TITLE
Is there any way to get long-lived access tokens?

### ISSUE THREAD

**Issue by TedHoward** [Microsoft/winsdkfb#25]
This is a very big deal. On Android & iOS, the official FB SDK somehow creates and renews long-lived access tokens. It appears that this WinRT FB SDK only grants short-lived tokens. That makes sense as it is simply a wrapper of the html FB auth flow.

Our app already contacts our server which converts this short-lived token into a long-lived token. But those still expire and it's not clear if we they auto-renew somehow. So once we implement things like FB gifting (this week) we also have to implement asking users to re-login to FB which will kill that UX funnel effectively killing FB integration for our app.

So.... if this FB SDK can one way or another handle these tokens like on Android & iOS that would be great.

**Comment by ekalbredneb** [comment]
The short answer is "we're working on it."  We can't get into specifics here, sorry, but we hope to soon be able to provide the same kind of token management that the official SDKs do.

As far as extending your tokens automatically, here's the relevant info from Facebook's current docs:

> Even the long-lived access token will eventually expire. At any point, you can generate a new long-lived token by sending the person back to the login flow used by your web app - note that the person will not actually need to login again, they have already authorized your app, so they will immediately redirect back to your app from the login flow with a refreshed token - how this appears to the person will vary based on the type of login flow that you are using, for example if you are using the JavaScript SDK, this will take place in the background, if you are using a server-side flow, the browser will quickly redirect to the Login Dialog and then automatically and immediately back to your app again.

> After doing the above you will obtain a new short-lived token and then you need to perform the same exchange for a long-lived token as above.

So in the most common case, you can expect to be able to refresh the token by calling LoginAsync again.  if your app still has permissions, the user will either see nothing, or a dialog will briefly appear then immediately disappear.  If you play with various apps which use Facebook login on a phone much, you'll inevitably see this sort of thing at some point.  You will even see it in apps and on platforms using the Official SDKs.

**Comment by TedHoward** [comment]
I would have to retry it to verify, but I believe when I tried that with
the WebAuthenticationBroker the WAB didn't understand the redirect. Or it
was a double-redirect. At any point, it didn't seem to work. And you're
right - Xaml WebView should be able to do the job. Now I just need to
carefully catch and handle expirations.

Thanks for the heads-up that you're trying to make token management easy on
WinRT. It's good to know you guys are trying hard to build platform parity
in so many ways - openssl, cmake, facebook, etc.

-ted

**Comment by yodurr** [comment]
FYI, we're still looking into this.

**Comment by mateuszjanczewski** [comment]
Any news about this one? Do you have any ETA to solve it?:)

**Comment by alakshmi1030** [comment]
Using SessionLoginBehavior::WebAuth as a parameter to the LoginAsync function from the develop branch of our SDK, it is possible to retrieve long-term SSO tokens upon authentication.

**Comment by alakshmi1030** [comment]
The WebAuth login behavior is now merged into the master branch.
