### ISSUE TITLE
Exception - Not a valid absolute URI  - At GraphPath ?

### ISSUE THREAD

**Issue by Excelion-M** [Microsoft/winsdkfb#256]
![exception](https://user-images.githubusercontent.com/25247648/31665829-da35c040-b352-11e7-937a-7caf81aef39a.png)

It was fine few days ago, and out of nowhere it started giving this. Before that, it was working fine for couple of weeks. If i ignore it and continue( few more time, because it gives it on every GraphPath I use) the program continues to work normally.

**Comment by adiviness** [comment]
This is by design, visual studio is showing you exception data for an exception that will eventually be caught and handled within the sdk.

**Comment by Excelion-M** [comment]
But what can I do to 'fix' it? I mean what I'm using is pretty much similar to all the examples?

**Comment by adiviness** [comment]
You can go to the Exception Settings in visual studio and turn off notifications on that exception. For visual studio 2015, it's at Debug -> Windows -> Exception Settings. In there, you should find a checkbox for that exception in question (Platform::InvalidArgumentException). For me it was under the C++ Exceptions. Uncheck that and you should no longer be notified about it.

**Comment by Excelion-M** [comment]
Thank you ^^

**Comment by PoisonousJohn** [comment]
@adiviness hey! Just took a look at the code: https://github.com/Microsoft/winsdkfb/blob/a74acffdc8311b0fced0f98b4db748f52db09ba7/winsdkfb/winsdkfb/winsdkfb.Shared/GraphUriBuilder.cpp#L42

Wouldn't it be better just to check that url starts with appropriate domain "https://graph.facebook.com/" ? 
So most of the cases would be without exception?
Using exceptions in that way is considered a bad practice. It causes performance overhead.
