### ISSUE TITLE
Which graph version APIs we are using for facebook UWP nuget package? 

### ISSUE THREAD

**Issue by hellodear** [Microsoft/winsdkfb#263]
Hi,

We have received a notification from facebook on our app developer page that you are using Graph v2.5 API which needs to be upgraded to v2.6 or higher.

We are using facebookSDK nuget package 7.0.6 version in our app for fb login as of now. We are now thinking to move to winsdkfb for login workflows. Can you please let us know on what graph API version we are? 

Let us know more info is required from our side.

**Comment by khouzam** [comment]
Hi @hellodear 

The nuget package is on v2.1 by default if you don't specify a version in your session. You can easily change the requested version when you create your session by calling and then all the calls will target the API version specified.


    FBSession::SetAPIVersion(Major, Minor)
    e.g.    mySession->SetAPIVersion(2, 6)

If you're going to change the API version you target, I would suggest moving to the most current one that works to avoid having to update it in the short term.

Thanks.

**Comment by EmilAlipiev** [comment]
v2.1 or v2.10 is the default version now? i am receiving a warning on facebook developer page as "Reminder: Graph API v2.9 will be deprecated on Jul 22, 2019. Please use the API Upgrade Tool to understand how this might impact your app."
