### ISSUE TITLE
Login Success request fails

### ISSUE THREAD

**Issue by ByronMayne** [Microsoft/winsdkfb#264]
As of today Facebook added a new field in the response for Login Success. Current winsdkfb expects

1. `access_token`
2. `expires_in`

however a new field called `reauthorize_required_in` was added to the response. The code that handles the response conceders this a fail. 

```
// FacebookAccessTokenData.cpp

FBAccessTokenData^ FBAccessTokenData::FromUri(
    Uri^ Response
    )
{
    bool gotToken = false;
    bool gotExpiration = false;
    bool gotBadField = false;
    String^ token;
    String^ expiration = nullptr;
    FBAccessTokenData^ data = nullptr;

    WwwFormUrlDecoder^ decoder = FBAccessTokenData::ParametersFromResponse(
        Response);

    for (unsigned int i = 0; i < decoder->Size; i++)
    {
        IWwwFormUrlDecoderEntry^ entry = decoder->GetAt(i);

        if (entry->Name->Equals(L"access_token"))
        {
            token = entry->Value;
            gotToken = true;
        }
        else if (entry->Name->Equals(L"expires_in"))
        {
            expiration = entry->Value;
            gotExpiration = true;
        }
        else
        {
            gotBadField = true;
        }
    }

    if (gotToken && gotExpiration && !gotBadField)
    {
        data = ref new FBAccessTokenData(token, expiration);
    }

    return data;
}

```

You will notice that the `gotBadField` flag gets set to true when it reads `reauthorize_required_in`. I don't think we should fail if we have unknown fields as this breaks any new changes.

**Comment by ByronMayne** [comment]
You can fix this by removing the `gotBadField` bool.

**Comment by ByronMayne** [comment]
https://developers.facebook.com/blog/post/2018/05/01/facebook-login-updates-further-protect-privacy/

**Comment by khouzam** [comment]
Thanks @ByronMayne 

We've updated our published package with your fix.
