### ISSUE TITLE
Login fails with error 4201

### ISSUE THREAD

**Issue by corradocavalli** [Microsoft/winsdkfb#265]
Our application using winsdkfb started returning error 4201 when LoginAsync is invoked.
Is there anything to update/align to make it working again?

**Comment by NSouth** [comment]
Has anyone found a solution to this issue? I'm also getting 4201 and have no idea why.

**Comment by khouzam** [comment]
Yes, I'm looking at this.

**Comment by NSouth** [comment]
By the way, a workaround for now seems to be logging in with `SessionLognBehavior.WebAuth`. What is the difference between this and the default?

**Comment by corradocavalli** [comment]
In my case, since all i needed was to login and get some basic user info I resorted to plain old WebAuthenticationBroker sample instead of using Toolkit.

**Comment by nickz1p** [comment]
I have same problem

**Comment by khouzam** [comment]
BTW, we've updated the package with the fix for the issue. The 0.15.0 version should address thanks.

Thanks.
