### ISSUE TITLE
C# Facebook Login

### ISSUE THREAD

**Issue by HoaLeMinh** [Microsoft/winsdkfb#273]
Hi,
I am using winsdkfb v0.15.0 from NuGet in my UWP desktop app (Windows 10). 

The instruction (http://microsoft.github.io/winsdkfb/index.html) doesn't match with the Facebook developer application settings now, however I tried to input all required fields.

My issue is that whenever calling LoginAsyn of FBSession, my app always raise an exception with "HRESULT: 0x8001010A (RPC_E_SERVERCALL_RETRYLATER)". 

Exception thrown at 0x74BA17D2 (KernelBase.dll): WinRT originate error - 0x8001010A : 'A COM call (IID: {638BB2DB-451D-4661-B099-414F34FFB9F1}, method index: 6) to an ASTA (thread 6428) appears deadlocked and was timed out.'

I would appreciate if anyone could help me to solve this issue or just confirm that this library is still working.

Thanks in advance.

Kind regards,
Hoa

**Comment by khouzam** [comment]
Hi @HoaLeMinh 

The SDK is working, I just tried our sample LoginCPP-UWP right now and I'm able to login properly. From the error message that you're showing, this looks like the call is not even getting out to Facebook. Can you share a little bit of details on your application? Are you using C# or C++? Which login method are you calling? This seems like you're calling Login, either on the wrong thread or that you're blocking the thread while waiting for the results.

Thanks

**Comment by HoaLeMinh** [comment]
Hi Khouzam,

Thank you for your fast response.

My UWP application is using C#. It intends to let user post his/her photo to his/her Facebook account.
I just made a very simple call to make sure that this library is still working. My C# code is as following:

1. When user clicks the button:
         private void Post_Click(object sender, RoutedEventArgs e)
        {
            //var result = Task.Run(() => Login()).GetAwaiter().GetResult();
            var result = Task.Run(async () => { return await Login(); }).Result;
        }

2. My "Login" method is using the sample code and remove some permissions:
        private async Task<bool> Login()
        {
            FBSession sess = FBSession.ActiveSession;
            sess.FBAppId = FBAppId;
            sess.WinAppId = WinAppId;
            List<String> permissionList = new List<String>();
            permissionList.Add("public_profile");
            //permissionList.Add("user_friends");
            //permissionList.Add("user_likes");
            //permissionList.Add("user_location");
            //permissionList.Add("user_photos");
            //permissionList.Add("publish_actions");
            FBPermissions permissions = new FBPermissions(permissionList);

            // Login to Facebook
            var result = await sess.LoginAsync(permissions);

            if (result.Succeeded)
            {
                Debug.WriteLine(sess.User.Id);
                Debug.WriteLine(sess.User.Name);
                return true;
            }
            else
            {
                //Login failed
                Debug.WriteLine("Login failed!!!");
            }
            return false;
        }

 It waits very long time at the code line:  "var result = await sess.LoginAsync(permissions);". This method causes timeout, I guess.

If it is working properly, the Facebook login box will be shown, won't it?  

Hope that my details is clear. Thanks in advance for your support.

Kind regards,
Hoa

**Comment by HoaLeMinh** [comment]
Hi Khouzam,

Thanks for your support. I could use LoginAsync now. 

Kind regards,
Hoa
