### ISSUE TITLE
Broken fb login from wstore using winsdkfb.

### ISSUE THREAD

**Issue by truthfinder** [Microsoft/winsdkfb#277]
Hello.

A couple of weeks ago we got broken fb login on wstore platform apps (both released and development versions). At the same time it works for other platforms (macos/ios/android). We use the last winsdkfb.

For DEV versions we receive messages:  (app id: 767969196665111.)
Login Error: There is an error in logging you into this application. Please try again later.
Pressing OK, then:
Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.

For PROD versions we receive messages: (app id: 1141997212478010)
Ошибка входа: При входе в это приложение возникла ошибка. Попробуйте позже.
Entering error. Try later.
Pressing OK, then:
К сожалению, эта функция сейчас не доступна: Во время обработки запроса возникла ошибка. Пожалуйста, попробуйте ещё раз позже.
Function not available now. Error during request. Try again later.

Pressing OK again makes no action. It's possible to close FB dialog window using dialog close button only. Which reports UserCancel error in Win Store API.

No any other messages or errors. No any way to find out what Domain/URL is really wrong for WSTORE version.

Also about API: why OK doesn't close fb dialog, why wrong domain/url is not reported in error (on ok for example)?

**Comment by johanlindfors** [comment]
We've had similar issues, caused by changes in the Facebook App settings which might restrict the allowed redirect url to be explicit to a specific url (or several explicit ones), then making sure the actual redirect url we send from the app is correct. It can be as easy as using http instead of https... Not a specific issue with the winsdkfb though.

**Comment by truthfinder** [comment]
I wrote to facebook and they redirect me here. Not their issus they said. But now it starts to work. No code changes, no settings changes. Thank you for support anyway.

**Comment by johanlindfors** [comment]
Quick comment, it might absolutely have been out of Facebook's hands as well. More likely it's the admin of the actual Facebook App which tested some settings. Unless the admin is you naturally...
