### ISSUE TITLE
Need to add a method on FBSession to re-request permissions.

### ISSUE THREAD

**Issue by ekalbredneb** [Microsoft/winsdkfb#3]
FB Login allows users to refuse permissions to apps on an individual basis.  In the event that a permission is refused that the app must have to function, FB has a mechanism built into the oauth dialog that lets an app "re-request" the required permission.  Not having this in the SDK will be a deal breaker for app authors.

**Comment by adiviness** [comment]
c76878059b0952cc572b8e6d991bc267aa667b57 fixes this issue.
