### ISSUE TITLE
Can't logout?

### ISSUE THREAD

**Issue by TedHoward** [Microsoft/winsdkfb#31]
I don't have a clean repro on this, but I can't get a clean logout.

I call FBSession::ActiveSession::Logout(), I see it succeed, I verify in Windows Explorer that the file is gone, I restart the app, call FBSession::ActiveSession::LoginAsync(), and no WebView UI seems to appear but LoginAsync returns with valid FBuser data for the log'ed out user.

Is the xaml WebView cacheing data? I always try to make sure not to check the Facebook 'stay logged in' checkbox to prevent this sort of scenario.

For customers of apps, this is an odd scenario so low-pri.
For development, I need to login in as 2-3 different users to test all our apprequest scenarios. So this ends up as critical until I can figure out a workaround. My current workaround is to wait 2 hours for the access token to expire.

**Comment by TedHoward** [comment]
Uninstalling the app works.
And I realized why I think it's a WebView cache issue. It always caches the username/email field. After uninstall, that field is empty.

**Comment by ekalbredneb** [comment]
FB login is strange in this instance.  The guidance from FB is that the app should cache its access token, which the SDK does, and upon a call to Logout it should delete the cached token but *not* force the user to go through the login UI again.  Which has never made sense to me, but appears to be how the official SDKs behave as well.  

If you wish to completely log a user out, i.e. force the login UI again, you can actually revoke your app's permissions.  See [the FB permissions docs] (https://developers.facebook.com/docs/facebook-login/permissions/#revoking) for the details.  I *believe* this will do what you want.

**Comment by villagra** [comment]
I have the same issue and revoking the app permissions doesn´t look right or make sense. I just want to allow my users just to logout so any other user can log in into the application using the same device, so far, the only option is uninstall the app and install it again. 
Is there any way to force the login ui again?

**Comment by TedHoward** [comment]
Thanks for the response, Blake.
I'm not surprised. Facebook is odd in many ways. I've been in their API since 2008 I think. It used to be far more painful but still isn't great.

@villagra, 
Uninstall works for development. For end-users ... the most you could hope for would be to clear the WebView's cookies or whatever it's using to remember the login information. That change won't make it into the official SDK as it's not what FB wants. And they could always deny your app due to violating their terms of service ... but I'm 100% certain that won't happen.

**Comment by yodurr** [comment]
SDK is following FB guidance.  Closing this issue.

**Comment by villagra** [comment]
To whomever might need it:
This is how you can force logout....

            var myFilter = new Windows.Web.Http.Filters.HttpBaseProtocolFilter();
            var cookieManager = myFilter.CookieManager;
            var myCookieJar = cookieManager.GetCookies(new Uri("https://facebook.com"));
            foreach (var cookie in myCookieJar)
            {
                cookieManager.DeleteCookie(cookie);
            }

**Comment by danielvieira43** [comment]
Even if you are following facebook guidance this sdk isn't well finished. This behavior is very annoying, user cannot switch accounts, the logout doesn't kill session/cache/cookie, but you close the issue. Nice piece of buggy software as you can see.

**Comment by TedHoward** [comment]
They chose to do what Facebook terms say should occur. If you are building an SDK for another company's API, would you choose to violate their terms? Facebook would not be pleased and may cooperate less with this Microsoft team. I'd prefer cooperation.

As for "buggy" I disagree. It's working well for our game. In fact, better than the official Android SDK which has some odd behaviors that I've now been tasked with fixing.

ps. This is my show of support for the Windows Facebook SDK team, not actually a rebuttal.

**Comment by bgmsd** [comment]
@villagra, your solution works perfectly for me. Thank you.
