### ISSUE TITLE
PM, not an issue: Did I fail to send 2 PRs to this repo?

### ISSUE THREAD

**Issue by TedHoward** [Microsoft/winsdkfb#32]
I thought I sent a couple of pull requests to this repo. I believe my comment on my PRs was something along the lines of "Whenever I do something new with git I do it wrong, and this is my first PR." I suspect I did it wrong. I just added data classes and fields to the Generated classes to support our use of Facebook in our cross-platform game.

Commit messages:
Added profile picture to FBUser data-driven serialization 
Added apprequest to data-driven serialization 

I'd love to help make this a great SDK. I live in Seattle, worked ~5yrs @ MSFT, and happy to meet to chat.

**Comment by austxcodemonkey** [comment]
Hey Ted, I don't see any branches or commits from you in the repo, so I'm not sure what's up.  Were you able to push to a branch successfully?  If so, what was the name of the branch?

**Comment by ekalbredneb** [comment]
Hey Ted, I don't see any branches or commits from you in the repo, so I'm not sure what's up. Were you able to push to a branch successfully? If so, what was the name of the branch?

**Comment by ekalbredneb** [comment]
Also I checked your profile on GH to see if maybe you'd actually forked the repo and pushed to that or something (this happened to me once accidentally), but don't see anything.

**Comment by ekalbredneb** [comment]
Hmm, so it turns out forking the repo and pushing to a branch there is actually the right thing to do.  When I attempted to push directly to microsoft/winsdkfb, I was denied access, so then I forked the repo, pushed my branch, and was able to successfully submit a PR.  Give that a shot and see how it turns out.
