### ISSUE TITLE
Missing info in FBUser after login

### ISSUE THREAD

**Issue by iloabn** [Microsoft/winsdkfb#36]
Greetings!

When using the facebook sdk to first log in with "public_profile" and "email" and then access the user using "FBSession.ActiveSession.User" there is only two requests being made.

1. //me
2. //%user_id%

This means that the FBUser class is only populated with ID and Name. Everything else is missing and I'm not finding anything in the documentation describing how to update the user or similar.

Am I supposed to update the FBUser using the FBSingleValue class or how is that class supposed to be populated?

Thanks in advance!
//Fabian

**Comment by ekalbredneb** [comment]
After successfully acquiring an access token, the FBSession class just asks for /me from the graph API, true.  I'm not certain what fields may or may not be available depending on how tightly the privacy settings are locked down in a person's account, but when I request /me for my own account with just public_profile and email permissions, the following fields are returned: id, first_name, gender, last_name, link, locale, timezone, updated_time, and verified.  To retrieve info beyond this, you will need to specify the fields in a PropertySet, and issue your own graph call using FBSingleValue.

Something like this:

    task<FBResult^> FBSession::GetUserInfo(
        Facebook::FBAccessTokenData^ TokenData
        )
    {
        PropertySet^ parameters = ref new PropertySet();

        parameters->Insert("fields", "albums.limit(5), posts.limit(5)");

        FBSingleValue^ value = ref new FBSingleValue(
            "/me",
            parameters,
            ref new FBJsonClassFactory([](String^ JsonText) -> Object^
            {
                return MyCustomFBUserObject::FromJson(JsonText);
            }));

        return create_task(value->Get());
    }

Where the class "MyCustomFBUserObject" is a class you've created by hand or generated, that knows how to serialize in the extra fields you're requesting.

[Issue #12](https://github.com/Microsoft/winsdkfb/issues/12) should be fixed soon and provide you with something that won't require a custom class in most cases, but for now if you want more than the basics, this is what you need.

Thanks,

Blake

**Comment by iloabn** [comment]
Thanks for the comment @ekalbredneb !
I ended up using the FBSingleValue to get the data I needed by specifying the fields I needed.

The interesting thing here is that you note that in the standard call to /me you get all those different fields. For me, this is the pure json that gets returned:

```
{
  "name": "Fabian Miiro",
  "id": "100002429266339"
}
```

I wonder what this could be an indication of, perhaps settings of the individual user on Facebook?
Looking forward to seeing #12 being finished.

I'll also look into where I think I can contribute, since this project is helping us same a lot of time.

Thanks again for your comment :)
