### ISSUE TITLE
Project will not build if the Solution Name / Filepath contains spaces

### ISSUE THREAD

**Issue by DesHuth** [Microsoft/winsdkfb#39]
I was getting build errors when I added the Facebook project to my c# app, reading through the errors it appeared that it was using an unquoted filepath with spaces in it.

Solved the problem with a bit of brute force by creating a blank project with no spaces in the name.  Facebook built OK and copied over to the intended project.

**Comment by mfmanca** [comment]
It's enough to go into the Project settings -> Build Events and add delimiters ("...") to the paths like 

pushd "$(ProjectDir)..\..\FBWinSDK\FBWinSDK.Shared"
call codegen.cmd
if not exist "$(TargetDir)fb_blank_profile_portrait.png" copy Images\fb_blank_profile_portrait.png "$(TargetDir)"
popd

**Comment by adiviness** [comment]
As of 6a18833dd130513d4a9422b934b967f7ab2cefaf this should be fixed.
