### ISSUE TITLE
Not able to refrence facebook sdk

### ISSUE THREAD

**Issue by aqibbanday** [Microsoft/winsdkfb#47]
Can you please tell me how can i add the reference as its not building and shows error. m stuck and confused

**Comment by ekalbredneb** [comment]
It might be hard to diagnose this problem based solely on the information you've provided, but there's one build error people have encountered that it's possible you've hit.  If you've seen a dialog box pop up and say something like "This file can't be run on Windows," you've probably run into a file copy issue with nuget.exe that we're trying to track down.  If you look in the \FBWinSDK\.nuget directory in the root of the SDK source tree, and there's a copy of nuget.exe there that is 0 bytes long, this is your problem.  To work around it, go to a command prompt, cd into \FBWinSDK\build\nuget in the SDK tree, run download-nuget.cmd, then copy FBWinSDK\build\nugget\nuget.exe to \FBWinSDK\.nuget and try your build in Visual Studio again.

If this is not the issue you're running into, please provide some more detail like the text of the error message you're hitting, and we'll attempt to diagnose further.

**Comment by aqibbanday** [comment]
I Am getting a bunch of errors when i build the project can you please send me a fixed facebook sdk.

**Comment by aqibbanday** [comment]
Severity	Code	Description	Project	File	Line
Error	MSB3073	The command "pushd D:\Download\Compressed\winsdkfb-master\winsdkfb-master\FBWinSDK\FBWinSDK\FBWinSDK.Windows\..\FBWinSDK.Shared
call codegen.cmd
if not exist D:\Download\Compressed\winsdkfb-master\winsdkfb-master\FBWinSDK\Debug\FBWinSDK.Windows\Images mkdir D:\Download\Compressed\winsdkfb-master\winsdkfb-master\FBWinSDK\Debug\FBWinSDK.Windows\Images
if not exist D:\Download\Compressed\winsdkfb-master\winsdkfb-master\FBWinSDK\Debug\FBWinSDK.Windows\Images\fb_blank_profile_portrait.png copy Images\fb_blank_profile_portrait.png D:\Download\Compressed\winsdkfb-master\winsdkfb-master\FBWinSDK\Debug\FBWinSDK.Windows\Images
popd
pushd D:\Download\Compressed\winsdkfb-master\winsdkfb-master\FBWinSDK\FBWinSDK\FBWinSDK.Windows\..\..\build\nuget
if not exist D:\Download\Compressed\winsdkfb-master\winsdkfb-master\FBWinSDK\FBWinSDK\FBWinSDK.Windows\..\..\.nuget\nuget.exe call download-nuget.cmd
if not exist D:\Download\Compressed\winsdkfb-master\winsdkfb-master\FBWinSDK\FBWinSDK\FBWinSDK.Windows\..\..\.nuget\nuget.exe copy nuget.exe D:\Download\Compressed\winsdkfb-master\winsdkfb-master\FBWinSDK\FBWinSDK\FBWinSDK.Windows\..\..\.nuget
popd
popd


:VCEnd" exited with code -1.	FBWinSDK.Windows	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	122

**Comment by aqibbanday** [comment]
Severity	Code	Description	Project	File	Line
Error	MSB3073	The command "pushd D:\Download\Compressed\winsdkfb-master\FBWinSDK\FBSDK-UWP\FBSDK-UWP\..\..\FBWinSDK\FBWinSDK.Shared
call codegen.cmd
if not exist D:\Download\Documents\Visual Studio 2015\Projects\FBDemo\Debug\FBSDK-UWP\fb_blank_profile_portrait.png copy Images\fb_blank_profile_portrait.png D:\Download\Documents\Visual Studio 2015\Projects\FBDemo\Debug\FBSDK-UWP\
popd

:VCEnd" exited with code 9009.	Facebook	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123

**Comment by adiviness** [comment]
Can you pull the latest changes and let me know if they fixed the issue you were having?

**Comment by aqibbanday** [comment]
Update the documentation

```
 On Wednesday, 2 September 2015 1:10 AM, adiviness <notifications@github.com> wrote:
```

 Can you pull the latest changes and let me know if they fixed the issue you were having?—
