### ISSUE TITLE
Can't login using LoginAsync on UWP app

### ISSUE THREAD

**Issue by bogdanbujdea** [Microsoft/winsdkfb#52]
I just started to use this SDK and I wanted to do a test app, but I can't login with Facebook. I get an exception from the FacebookDialog class. Here is my code:
```
 FBSession session = FBSession.ActiveSession;
 session.FBAppId = "<fb app secret>";
 session.WinAppId = "<app id>";
            
 var fbResult = await session.LoginAsync(new FBPermissions(new List<string> { "email" }));
```
Here is a screenshot with the exception: http://prntscr.com/871c6b

**Comment by adiviness** [comment]
I was not able to reproduce this, are you still encountering this problem?

**Comment by alakshmi1030** [comment]
Please reopen if you are still encountering this problem.
