### ISSUE TITLE
Consistent Project Naming [breaking change]

### ISSUE THREAD

**Issue by adiviness** [Microsoft/winsdkfb#55]
There's currently multiple names for the project:

|  Type  |   Name  |
|----------|-----------|
| git repo | winsdkfb |
| visual studio sln/proj files | FBWinSDK |
| output binaries | Facebook.* |

These should all be standardized to one name. This will likely break references to the project or output binaries. Any comments on this breaking change are welcome.

**Comment by yodurr** [comment]
Change to the following yes?

|  Type  |   Name  |
|----------|-----------|
| git repo | winsdkfb |
| visual studio sln/proj files | winsdkfb |
| output binaries | winsdkfb.* |

**Comment by adiviness** [comment]
That is correct.

**Comment by yodurr** [comment]
go forth and rename! :)

**Comment by adiviness** [comment]
d011d939bce005016dc34130f4989aa46c2a3ac3 closes this issue.
