### ISSUE TITLE
call of LoginAsync() crashes with ComException when called after ShareTargetActivation 

### ISSUE THREAD

**Issue by MSiccDev** [Microsoft/winsdkfb#60]
I am trying to refresh the AccessToken when it is expired before letting the user share to Facebook. however, I am getting this exception in a Windows 10 UWP:

WinRT information: A COM call (IID: {638BB2DB-451D-4661-B099-414F34FFB9F1}, method index: 6) to an ASTA (thread 520) was blocked because the call chain originated in or passed through another ASTA (thread 5448). This call pattern is deadlock-prone and disallowed by apartment call control.
Additional information: A COM call to an ASTA was blocked because the call chain originated in or passed through another ASTA. This call pattern is deadlock-prone and disallowed by apartment call control.

I can call the method without any problems when the application is launched normally.

How can I get around this? I have referenced the GitHub repo which I stored locally.

**Comment by BrandonLive** [comment]
At first glance this looks like a bug in the SDK.

From void FacebookDialog::InitDialog():
CoreWindow^ wnd1 = CoreApplication::MainView->CoreWindow;

This shouldn't be looking for the MainView when called from a hosted view. This could maybe use CoreApplication::GetCurrentView, but if it just needs the CoreWindow then just using CoreWindow::GetForCurrentThread, assuming you are meant to only call this from UI threads.

If LoginAsync has a silent / no UI mode, then it shouldn't be trying to create a dialog at all in that case. Or if it doesn't have that and just needs to renew a token or something, then someone should add that.

**Comment by MSiccDev** [comment]
unfortunately, both of the suggested solutions do not work, throwing AccessViolationException. I'm moving on with some manual implementations now until this resolved.

**Comment by BrandonLive** [comment]
Hmm, that doesn't sound right. What's the source/callstack of the AV?

**Comment by MSiccDev** [comment]
Sorry, I removed this version of the SDK and wrote my own code, so I can't reproduce it any longer without some effort.

**Comment by adiviness** [comment]
If this is still affecting you please reopen the issue, we're unable to repro it currently.
