### ISSUE TITLE
FQL support?

### ISSUE THREAD

**Issue by igrali** [Microsoft/winsdkfb#61]
Is it possible to make FQL queries using this SDK?

I know that the last version of Facebook API where FQL is available is v2, but v2 will be supported until August 2016, so being able to make the FQL calls when porting from 8.1 to UWP would be quite helpful.

**Comment by igrali** [comment]
Oh, OK, after some experimenting, I see that I can use FBClient to make the call to fql endpoint.

**Comment by igrali** [comment]
I wrote a blog post about it if anyone else has troubles making FQL queries:

http://igrali.com/2015/10/01/make-fql-queries-from-the-latest-windows-10-facebook-sdk/

**Comment by khouzam** [comment]
Thanks Igor,

That's a great post.

~Gilles
Sent from my Windows Phone
________________________________
