### ISSUE TITLE
Can the Facebook popup be silenced when Like button is invoked?

### ISSUE THREAD

**Issue by shanebweaver** [Microsoft/winsdkfb#62]
In a recent presentation, it showed the SDK caused a Facebook popup/redirect when the Like button was invoked. Can this popup be silenced?

Thanks

**Comment by alakshmi1030** [comment]
We will look into this soon - right now we haven't finalized the exact details of the Like button flow. Thanks for the question!

**Comment by alakshmi1030** [comment]
After investigation, while our SDK supports the "Like" Action as seen in our documentation (http://microsoft.github.io/winsdkfb/#like_page), the Page Like functionality as seen through Facebook's "Like" button is actually not an open API call we can use.

See this page on Facebook's developer docs for more info:https://developers.facebook.com/docs/opengraph/guides/og.likes
