### ISSUE TITLE
invalid app id in C# UWP Application 

### ISSUE THREAD

**Issue by thorizer** [Microsoft/winsdkfb#66]
I have a 100% valid app id which works with my webauthetificationbroker . I even checked once more on my facebook app dashboard.
But when i use the fb sdk to login I get an "invalid app id" error.

**Comment by alakshmi1030** [comment]
Are you talking about the Windows Store (SID) app ID, Windows Phone app ID, or the actual Facebook app ID? All three need to be configured correctly for the app to work. See here for reference: http://microsoft.github.io/winsdkfb/#getting_started

**Comment by thorizer** [comment]
I'm talking about the Facebook app ID . 
sess.FBAppId = "<My Facebook App ID>";
the error : "invalid app id <My Facebook App ID>

**Comment by alakshmi1030** [comment]
Can you share source code or screenshots of code + Facebook app developer portal to show error? I can't repro on my end.

**Comment by khouzam** [comment]
Please reopen this issue if you are still having the problem.

**Comment by khouzam** [comment]
Please reopen if you're still seeing the issue.
