### ISSUE TITLE
C++ UWP - FeedDialog Empty in a specific sequence

### ISSUE THREAD

**Issue by AlanGusLive** [Microsoft/winsdkfb#67]
Hi,

I use the sample "LoginCpp-UWP.sln". I added a button "FeedDialob FB" in the main page to display a FeedDialog and in a specific sequence the FeedDialog is empty with only the close button. I removed the navigation to the OptionsPage.

The sequence is :

- Launch the application
- Press the "Login To FB" button (enter your login/password)
- Press the "FeedDialog FB" button (=>OK, I can see the FeedDialog with facebook interface)
- Close the application (without log off)
- Launch the application
- Press the "Login To FB" button (no need to enter the login/password because the Access Token is valid)
- Press the "FeedDialog FB" button (=>Problem, I can see only an empty Feeddialog with the close button).

The source code of the project is available here : http://1drv.ms/1LAK63w

The project solution is "Facebook - FeedDialog\samples\LoginCpp-UWP\LoginCpp-UWP.sln"
You need to configure the Resources.resw (FBApplicationId and FBWindowsAppId)
Can you reproduce the bug or why the FeedDialog is empty?

Regards,
AlanGusLive

=>OK
![facebook - feeddialog success](https://cloud.githubusercontent.com/assets/15076413/10417466/c6f042c2-703c-11e5-83de-b118674690d9.png)

=>Problem
![facebook - feeddialog failed](https://cloud.githubusercontent.com/assets/15076413/10417462/b3e46e7e-703c-11e5-8401-b1901d4cd6d4.png)

**Comment by adiviness** [comment]
I was able to reproduce this. The sdk sends the exact same request to facebook's servers, however the 2nd time (with the blank dialog) the server is responding with http status code 500 (internal server error). We'll need to investigate more to see if this is a problem with facebook or if the sdk should be notifying them of a canceled request. The sdk should also be more explicit about the error rather than letting the blank dialog just sit there.

**Comment by adiviness** [comment]
I was testing this again today and I am no longer able to reproduce the problem. Are you still encountering it?

**Comment by AlanGusLive** [comment]
Yes, I still have the problem. May be you can test with my Resources.resw?
I tested with Windows 10, Debug and x86.

You can find the Resources.resw here: http://1drv.ms/1OJ7sJt

**Comment by khouzam** [comment]
The issue seems to be sporadic. We're still investigating possible fixes.

**Comment by AlanGusLive** [comment]
I used Fiddler2 to investigate. When I log to facebook with a login/password the number of cookies after the login_success are different than when I log by using the access token. I noticed the v2.4 is used for the connection with login/password "GET /v2.4/dialog/oauth?redirect_uri=...".

The FeedDialog works after a connection using a login/password:
![facebook - fiddler success](https://cloud.githubusercontent.com/assets/15076413/10560038/b8b7fa3a-74fe-11e5-9cef-d9c0b5d91ac4.png)

The FeedDialog failed after a connection using the access token:
![facebook - fiddler failed](https://cloud.githubusercontent.com/assets/15076413/10560039/c89e7a32-74fe-11e5-917e-a841e964b5ca.png)

I tried to resend the failed FeedDialog request by adding manually with Fiddler the 2 following cookies and it works:
"c_user=100008100693181; xs=135%3AZ0vvJ8Vl-F0C7A%3A2%3A1445097204%3A-1;"

I will tell you if I find something else.

**Comment by AlanGusLive** [comment]
Hi,
 
I have configured another sample to get an empty FeedDialog on Windows 10 (PC). I used the latest version of the winsdkfb. I have just change 2 things in MainPage.xaml.cpp:
- I removed 4 requested_permissions
- I added the parameter SessionLoginBehavior::ForcingWebView in the call of the function LoginAsync(...)
 
I have created a facebook test account and configured a new application "FeedDialogUWP".
The "Resources.resw" is already configured with the correct values.
I added for your test a text file in the zip source code with the login/password to connect to Facebook ("Login & Password to use for the test.txt").
If you need you can use it to modify the configuration of the application in https://developers.facebook.com
 
To get the empty FeedDialog, the sequence is:
- Get source code on : http://1drv.ms/1WCNgPu
- Open the project solution:"Facebook - FeedDialogUWP\samples\LoginCpp-UWP\LoginCpp-UWP.sln"
- Launch the application
- Press the "Login To FB" button (enter the login/password from the file "Login & Password to use for the test.txt" in the zip)
- Press the "Dialogs" button
- Press the "Feed" button (=>OK, I can see the FeedDialog with facebook interface)
- Close the application (without log off)
- Launch the application
- Press the "Login To FB" button (no need to enter the login/password because the Access Token is valid)
- Press the "Dialogs" button
- Press the "Feed" button (=>Problem, I can see only an empty Feeddialog with the close button because I received a HTTP/1.1 500 Internal Server Error).
 
For your information the program works perfectly with the Windows 10 Mobile emulator and with the Windows 10 Mobile device.
 
Can you reproduce the bug? Do I need to "Report New Bug" in https://developers.facebook.com/bugs/ ?
 
Regards,
AlanGusLive

**Comment by AlanGusLive** [comment]
Hi,

For your information, I have created a bug report on facebook site: https://developers.facebook.com/bugs/886890504752147/

Regards,
AlanGusLive

**Comment by AlanGusLive** [comment]
Hi,

The answer of Facebook support has not help me, but I found that to display the FeedDialog in my sequence without have an error 500, I just need to add the cookies "c_user" et "xs" in the cookieManager before the call of the navigate function from the Webview and it works.

You can now close this issue if you don't need more information.

Regards,
AlanGusLive.

**Comment by alakshmi1030** [comment]
I see, thanks for the information. We'll look into your solution of adding the cookies before the navigate function call.

**Comment by TedHoward** [comment]
Can you provide your code? Based on your comments, I can figure it out but it would take a day of work since I'm not familiar with this codebase. If you provide a pull-request, however, I could take advantage of your progress on this bug.

**Comment by AlanGusLive** [comment]
Hi TedHoward,

I shared my code in a zip file available with this link : http://1drv.ms/1Oxfvve
In the zip file I added 2 html files, so you can directly see the comparaison between my source code and the latest sdk source code.

For your information, in my code, I use a define "PLATEFORM_W10M" when I compile the ARM version for Windows 10 Mobile.

Regards,
AlanGusLive
