### ISSUE TITLE
C++ winsdkfb Documentation - Wrong double quote

### ISSUE THREAD

**Issue by AlanGusLive** [Microsoft/winsdkfb#69]
Hi,

In the winsdkfb documentation (http://microsoft.github.io/winsdkfb/), in the section "Feed dialog" and "C++", you can find a wrong double quote with the last double quote for the line:

parameters->Insert(L"link", L"https://www.microsoft.com/en-us/default.aspx”);

Can you please replace the line by:

parameters->Insert(L"link", L"https://www.microsoft.com/en-us/default.aspx");

Regards,
AlanGusLive

**Comment by adiviness** [comment]
Thanks for letting us know! This should be fixed as of 0f2fea8d8a74cf4d2f97655528e9e685320bd5d0
