### ISSUE TITLE
Create a scrumptious or equivalent full tutorial

### ISSUE THREAD

**Issue by sanjeevdwivedi** [Microsoft/winsdkfb#73]
Create a basic tutorial that shows the flow of various APIs such as 

1. Login
2. Asking for permissions
3. Showing user picture using the picture control
4. Showing user's friends with the Friend Picker
5. Showing a place picker 
6. Posting to Facebook.

You can look at the the following tutorial for reference http://facebooksdk.net/docs/windows/tutorial/

**Comment by alakshmi1030** [comment]
Thanks for the suggestion - we are planning on creating a more in-depth tutorial similar to your scrumptious one.

**Comment by alakshmi1030** [comment]
The sample app/tutorial is now live on our new documentation site at this URL:

http://microsoft.github.io/winsdkfb/sample/
