### ISSUE TITLE
API too limited

### ISSUE THREAD

**Issue by ThaineNorris** [Microsoft/winsdkfb#75]
I have a successful Windows 8.1 Store App that I am trying to update as a UWP app. My app is a photo booth which allows users to post their photo booth pictures on Facebook. They can post in three ways:

1. Each user can post to his own personal page, requiring a FB login for each photo session.
2. Users can post to the host's personal page (such as a bride or groom or birthday boy/girl). The host logs into the software once at the beginning.
3. Users can post to a product or group page that is administered by the host. The host logs in at the beginning and selects to which of his pages he wants images to go.

Scenario 3 is extremely important as it is presently the most frequently used. However, I cannot see how this can be done with this new FB SDK.

With the old SDK, I could get a list of pages belonging to the user account by sending a "me/accounts" request which returned a JSON array of user-administered pages. I could then get a separate access token for each page. I could then create a FacebookClient object with the proper access token and all image posts would go to the selected product or group page.

How can this be accomplished with this new FB SDK?

Thank you and best regards,
Thaine Norris

**Comment by alakshmi1030** [comment]
Hello Thaine,

I see your point/question. Currently, the FB SDK does support any Graph API call that needs to be made. You can see an example here: http://microsoft.github.io/winsdkfb/#like_page. Note that the way the Graph API path is modified is through the path variable. For what you are mentioning in scenario 3, this would translate to:

<code>
string path = user.Id + "/accounts";
</code>

This is assuming that the "manage_pages" permission was approved by the user. Once you use the Graph API request to get the JSON response of user-administered pages, you can then loop through and obtain the access token. Our FBClient class is not the same as the FacebookClient object you are mentioning from the old FB SDK. You would likely have to initiate more Graph API requests with the saved page access tokens using this endpoint:
https://developers.facebook.com/docs/graph-api/reference/page/photos/

For regular posts on a Facebook page, see this endpoint reference:https://developers.facebook.com/docs/graph-api/reference/v2.5/page/feed

Does this answer your question?

**Comment by ThaineNorris** [comment]
Thank you for your speedy reply! 

I will try what you describe and see if I can make it work.

**Comment by alakshmi1030** [comment]
You can try this:

public class FBReturnObject
    {
        public string Id { get; set; }
        public string Post_Id { get; set; }
    }

**Comment by khouzam** [comment]
Please reopen if you're still having issues.
