### ISSUE TITLE
Cannot find FBReturnObject

### ISSUE THREAD

**Issue by BonyYousuf** [Microsoft/winsdkfb#77]
Hi,
the documentation for using graph api requires a class called "FBReturnObject" but I could not find any reference to this class anywhere. 
Documentation also says "A class will have to be created (FBReturnObject in this example) to receive and parse the json response."
But how do I create this class?

Can anyone help?

**Comment by BonyYousuf** [comment]
I have created a class like this as it was mentioned on another thread.

public class FBReturnObject
    {
        public string Id { get; set; }
        public string Post_Id { get; set; }
        
    }


but I am not sure what to do next. How will this class return json text with FBReturnObject.FromJson
and how is this class called/instantiated? If I knew that then maybe I can figure out a way to get json from id and post_id. But the lack of example makes it very confusing. 
Do you have a working C# example that I can look at for graph post?

**Comment by alakshmi1030** [comment]
Hello, yes we are planning to update the documentation around this. For now, this should work with the FBReturnObject to get you a result JSON (example assuming you have a path and parameters as specified in one of the code samples)

var factory = new FBJsonClassFactory(s => {
                    return JsonConvert.DeserializeObject<FBReturnObject>(s);
});

var singleValue = new FBSingleValue(path, parameters, factory);
var result = await singleValue.PostAsync();
if(result.Succeeded)
{
     //do something
}

**Comment by BonyYousuf** [comment]
Thanks :)
