### ISSUE TITLE
UWP - SDK ignoring timezones -> returning bad accesstoken

### ISSUE THREAD

**Issue by plokijuma** [Microsoft/winsdkfb#78]
Hello

I had made successful login earlier. My accesstoken is about to expire.
I experienced a strange behaviour.

I cannot log in now. No popup showing. i see just some logs at output when i call:
FBResult result = await sess.LoginAsync(permissions);

__Console output__
Access Token:  *****
Token expires at ?2015?. ?október? ?27?., ?kedd, ?18?:?00?:?09
FBResult destructor
Content-Type: multipart/form-data; boundary=------------------------------fbsdk1234567890
FBResult destructor

__FBResult object  has an error object, thats why its result false:__
_type = L"OAuthException"
_message = L"Error validating access token: The session was invalidated explicitly using an API call."

That error can be connected with wrong culturalinfo / timezone handling. I think sdk thinks that the access token is still valid while it is not valid anymore...

__Token expires at ?2015?. ?október? ?27?., ?kedd, ?18?:?00?:?09
Current time : 2015.oktober 27. 16:42 CET__

When i set date on local machine to 28th october, the sdk shows the popup and i could log in.

**Comment by adiviness** [comment]
What login method were you using to hit this problem?

**Comment by plokijuma** [comment]
Uh. that was a long time ago.
I guess it was a webview method on desktop (x86) UWP app.
I could recreate the issue by manipulating system time.

**Comment by adiviness** [comment]
I am unable to reproduce this, no amount of changing to the timezone/system clock seems to trigger this problem for me. If you are still observing this problem please reopen this issue. A set of steps to repro the problem would be very helpful as well.
