### ISSUE TITLE
Documentation for Win10 is misleading

### ISSUE THREAD

**Issue by tomfurrier** [Microsoft/winsdkfb#79]
The documentation (http://microsoft.github.io/winsdkfb/) says:

"NOTE: For Win10, you can always use the PhoneProductId from the manifest to get the WinAppId instead of having one Windows Store ID and one Windows Phone Store ID."

I think it is misleading, it might work during development but for a published app the PhoneProductId did NOT work for me, and is not used in the LoginCpp-UWP sample either. 

The correct way is to go with the package SID on W10 as well.

**Comment by alakshmi1030** [comment]
Updated documentation per your comment.
