### ISSUE TITLE
ShowRequestsDialogAsync() doesn't return number of friends invited

### ISSUE THREAD

**Issue by BonyYousuf** [Microsoft/winsdkfb#80]
Hi,
On javascript SDK I AppRequest dialog returns the number of people that was invited with the dialog. However with ShowRequestsDialogAsync() I could not find any way to get that number.

Is there way I can get the number of friends that was invited?

**Comment by BonyYousuf** [comment]
The same is true for Feed dialog, it also don't return the post id.

**Comment by adiviness** [comment]
These are supported features of the sdk. When you call `ShowFeedDialogAsync` or `ShowRequestsDialogAsync`, an `FBResult^` object is returned. If `FBResult->Succeeded` is true, then you can cast the `FBResult`'s `Object` field to either a `FBFeedRequest^` or `FBAppRequest^`, respectively. From there you can access the information you're looking for.

**Comment by BonyYousuf** [comment]
Thanks
