### ISSUE TITLE
FBUser.location does not contain location data

### ISSUE THREAD

**Issue by sanjeevdwivedi** [Microsoft/winsdkfb#86]
The location attribute does not contain the city/state/zip/lat/longitude data..

**Comment by zory** [comment]
It is not just with Location object, but with other object's as well, for example - picture or age_range.

It can be "fixed" by adding properties in FBSession::GetUserInfo :

PropertySet^ propSet = nullptr;
	propSet = ref new PropertySet();
	propSet->Insert(L"fields", L"id,email,picture,location,age_range,first_name,gender,last_name,link,locale,name,timezone,updated_time,verified");  //<- all fields you need

P.S.: I am using 2.1 API on facebook app. Behaviour may slightly differ with version.

**Comment by alakshmi1030** [comment]
Thanks for the suggestions- we are planning to add in more properties as you both have suggested. 
@zory in the meantime if you want to submit a pull request we can include the modifications to the properties into our source faster.

**Comment by alakshmi1030** [comment]
After some investigation, you are able to pull the user's location by name at least using our SDK. However, in Graph API v2.5 the method to retrieving lat/long from a User's profile location information is very unclear. Here is the documentation on the Location node: https://developers.facebook.com/docs/graph-api/reference/location/

If you are able to figure out the correct Graph API request URL please let us know and then we can try and get a working code sample using our SDK.
