### ISSUE TITLE
UWP - Windows 10 Mobile - Crash upon login

### ISSUE THREAD

**Issue by Whyser** [Microsoft/winsdkfb#89]
Hello,

My project is an empty Universal App, where I just included the FBSDK-UWP-project and then referenced it. I followed the instruction in the documentation (and it works for x86 devices) but I get the following error when trying call LoginAsync(...) using a Windows 10 Mobile device (ARM).

`System.ArgumentException: Value does not fall within the expected range.`

Sorry that I can't provide more details, but I don't seem to be able to get more when the it breaks in App.g.i.cs. 

I managed to get a few more details when building from Unity:
`Exception thrown: 'System.ArgumentException' in mscorlib.ni.dll`
`Exception thrown: 'System.ArgumentException' in mscorlib.ni.dll`
`Unhandled 'Platform.InvalidArgumentException' exception caught! - 'The parameter is incorrect. Value does not fall within the expected range.'. Sender: '<null>'. Missing try/catch block.` - I suspect some of the text in this error is added by Unity, but I'm unsure.

And as I said the exact same code runs flawless on x86 devices. The code also works fine in an Windows 10 Mobile emulator (not ARM for obvious reasons). Has anyone else manage to build and login on an UWP app for an ARM device?

Please take a look at this ASAP! :)

**Comment by Whyser** [comment]
Okay, I found the issue. But it's still a bug. :/

It seems I hadn't enabled WiFi on the device and that is what caused the crash, with a really bad error message.

**Comment by alakshmi1030** [comment]
Is this an exception due to the fact that there was no network connection?

**Comment by Whyser** [comment]
It seems that way, can double check tomorrow.

**Comment by Whyser** [comment]
I'm so lost right now. 

Not sure if this issue got solved in the `develop` branch or if it was some random crash caused by something else. I can't re-create it in the `develop` branch any way (by toggling WiFi on or off). However, the Login-dialog that is shown is completely white when no WiFi is available, not sure what the intended behavior should be.

**Comment by alakshmi1030** [comment]
It sounds like your issue was resolved - I understand your confusion. There is a known HTTP 500 error that comes from the Facebook server side that sometimes causes a crash but in most cases a completely blank Login dialog as you have seen. This issue is intermittent and we are still trying to figure out how to fix it. Otherwise, I would say you have to just wait and try again after some time.

**Comment by adiviness** [comment]
I was not able to reproduce this, please reopen if you are still being affected by the issue.
