### ISSUE TITLE
UWP - Invalid user id. Share fails...

### ISSUE THREAD

**Issue by Whyser** [Microsoft/winsdkfb#91]
I have logged in successfully and are then trying to share a link. Resulting in the following error:

![wp_ss_20151120_0001](https://cloud.githubusercontent.com/assets/6816092/11303180/d4a47ddc-8fa1-11e5-83b6-d18794b47b0c.png)

Any help or suggestions to might be wrong?

**Comment by adiviness** [comment]
What permissions is your app requesting? Could you share the relevant code snippet? What branch are you building the sdk from?

**Comment by Whyser** [comment]
I init my doing this:

`FBSession facebookWindows = Facebook.FBSession.ActiveSession;
facebookWindows.FBAppId = appId;
facebookWindows.WinAppId = Windows.Security.Authentication.Web.WebAuthenticationBroker.GetCurrentApplicationCallbackUri().ToString();`

I login by doing this:

`FBPermissions permissions = new FBPermissions(new List<string>())
FBResult fbResponse = await facebookWindows.LoginAsync(permissions);`

Then after successful login i call this:

`PropertySet parameters = new PropertySet();
parameters.Add("toID", toId);
parameters.Add("link", link.AbsoluteUri);
parameters.Add("linkName", linkName);
parameters.Add("linkCaption", linkCaption);
parameters.Add("linkDescription", linkDescription);
parameters.Add("picture", picture);
parameters.Add("mediaSource", mediaSource);
FBResult fbResponse = await facebookWindows.ShowFeedDialogAsync(parameters);`

**Comment by alakshmi1030** [comment]
I just tried to repro your bug with the code snippet you provided and everything worked fine - do you think it was a temporary block in service from Facebook? Additionally, I'm not sure if all of your parameters would work necessarily - the ones listed on our documentation are "title", "link", and "description".

**Comment by adiviness** [comment]
Please feel free to reopen this issue if you are still being affected by it.
