### ISSUE TITLE
Exact same code fails on WP8.1 but not on W10Mobile

### ISSUE THREAD

**Issue by Whyser** [Microsoft/winsdkfb#92]
As the topic says. Exact same code fails on Windows Phone 8.1 using the winsdkfb for Windows 8.1 (and Phone) SDK, but it will work for Windows 10 Mobile.

I really don't know how anyone can succeed in using this SDK when I seem to fail so miserable.

The code that fails is trying to login exactly as mentioned in the documentation. On Windows 10 Mobile it will bring up the Login-dialog and let me login and get a successful response. On Windows Phone 8.1 it will bring the exact same error I mentioned in another issue (see https://github.com/Microsoft/winsdkfb/issues/89).

`System.ArgumentException: Value does not fall within the expected range.`

EDIT:

Tried using the `develop` branch instead. With some hazzle (build errors here and there) I manage to deploy using this branch instead. The Login in now seems to half-way work. It now shows the dialog on both OS:es but I am presented with a Facebook-dialog which says:

"Given URL is not permitted by the Application configuration. One or more of the given URLs is not permitted by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of the one of the App's domains." - Uhm, I have no clue what am I supposed to do with this error? :/

(And yes, I've configured the `Windows Store ID` and `Windows Phone Store ID` on Facebook)

**Comment by alakshmi1030** [comment]
Do you have Embedded Browser Oauth login set to "Yes" within your app Settings->Advanced tab in the Facebook Developer portal for your app?

**Comment by Whyser** [comment]
Yes I have enabled every login available on the "advanced tab".

**Comment by alakshmi1030** [comment]
You now need to set a Valid OAuth Redirect URI in the Advanced Settings tab of your app on the Facebook developer portal.

This URL is: http://www.facebook.com/connect/login_success.html

**Comment by adiviness** [comment]
Feel free to reopen the issue if this is still affecting you.
