### ISSUE TITLE
Windows 10 Universal App - auth_type reauthenticate ?

### ISSUE THREAD

**Issue by bgmsd** [Microsoft/winsdkfb#95]
I am having a problem logging out so that another user can log back into my universal app. This is not a web based app. The logout actually seems to work, but I cannot seem to get the login form to pop-up again, and if I exit the app and then reload it, the same user is automatically logged back in. So, I am trying to make something like the following code work to force a new user to be able to log in. This may be way off base, but there isn't much info about it. I am trying to follow along with this page. 
https://developers.facebook.com/docs/facebook-login/reauthentication

Here is my code, but it gives an error
private async void LoginAsNewUser(object sender, RoutedEventArgs e)
        {
            PropertySet parameter = new PropertySet();
            parameter.Add("auth_type", "reauthenticate");
            FBResult result = await sess.ShowRequestsDialogAsync(parameter);

        }

If I inspect result, I get the following:
ErrorInfo: 
Code: 4021
ErrorUserMessage: User canceled the Dialog flow
Message: Operation Canceled
Type: OAuth Exception

Any help would be appreciated

David

**Comment by adiviness** [comment]
#31 and #81 contain previous discussion related to this.

**Comment by bgmsd** [comment]
@adiviness, thank you. I found the solution in #31.
