### ISSUE TITLE
Long-lived token refreshes require users to re-enter their credentials and see UI

### ISSUE THREAD

**Issue by dankearney** [Microsoft/winsdkfb#99]
Using a server-based long-lived token generation flow like the ones supported by [Facebook](https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension) a user's Facebook access token expires after 60 days. Using this SDK, a user needs to re-enter their credentials and interact with the UI to get a new Facebook token, which is an inferior UX than other clients like Web, iOS, and Android have.

**Comment by TedHoward** [comment]
fyi, https://github.com/Microsoft/winsdkfb/issues/25

**Comment by alakshmi1030** [comment]
We are aware of this issue and are working to resolve it

**Comment by mateuszjanczewski** [comment]
Any news about this one? Do you have any ETA to solve it?:)

**Comment by alakshmi1030** [comment]
@dankearney are you guys seeing auto-regeneration of long term tokens now using WAB? For reference @mateuszjanczewski, if you pull from the develop branch of our SDK and set the SessionLoginBehavior to WebAuth, it will use the WebAuthenticationBroker which provides a long-term, SSO token by default. We haven't been able to confirm if the access token auto-renews after 60 days like the iOS/Android official SDK's.

**Comment by adiviness** [comment]
Please feel free to reopen this issue if this problem is still occurring.
